// Phase J1: the Pub/Sub oracle programs. Every program runs on a fresh
// official emulator (`cloud-pubsub-emulator-0.8.33`) and is a sequence of
// steps over gRPC (`google.pubsub.v1` services through grpc-js with the
// client library's protos) or HTTP/JSON on the same port, plus timing and
// push-endpoint steps. `{{template}}` strings resolve at run time against the
// values earlier steps produced (message ids, ack ids, revision ids, the
// push endpoint's origin, the current time).
import type { Json, ServiceName } from "./client.ts";

export type { Json };

export const PROJECT_ID = "fireside-pubsub-oracle";
export const PROJECT = `projects/${PROJECT_ID}`;
export const OTHER_PROJECT = "projects/fireside-pubsub-other";
const T = `${PROJECT}/topics`;
const S = `${PROJECT}/subscriptions`;
const SNAP = `${PROJECT}/snapshots`;
const SCHEMA = `${PROJECT}/schemas`;

export interface GrpcStep {
  readonly id: string;
  readonly note?: string;
  readonly grpc: { readonly service: ServiceName; readonly method: string; readonly request: Json };
  /** Client deadline; long-polling pulls use a shorter one. */
  readonly deadlineMs?: number;
  /** The order of a redelivery after several leases expired together is not a contract. */
  readonly sortReceived?: boolean;
}

export interface HttpStep {
  readonly id: string;
  readonly note?: string;
  readonly http: { readonly method: string; readonly path: string; readonly body?: Json | string };
}

export type StreamAction = { readonly write: Json } | { readonly waitMs: number } | { readonly end: true } | { readonly cancel: true };

export interface StreamStep {
  readonly id: string;
  readonly note?: string;
  readonly stream: { readonly service: ServiceName; readonly method: string; readonly actions: readonly StreamAction[] };
}

export interface SleepStep {
  readonly id: string;
  readonly note?: string;
  readonly sleepMs: number;
}

export interface PushesStep {
  readonly id: string;
  readonly note?: string;
  /** Waits until at least `atLeast` push requests landed (or the timeout) and records them all. */
  readonly pushes: { readonly atLeast: number; readonly timeoutMs: number };
}

export interface PushStatusStep {
  readonly id: string;
  readonly note?: string;
  /** The HTTP status the push endpoint answers with from now on. */
  readonly pushStatus: number;
}

export type Step = GrpcStep | HttpStep | StreamStep | SleepStep | PushesStep | PushStatusStep;

export interface Program {
  readonly id: string;
  readonly category: string;
  readonly title: string;
  readonly steps: readonly Step[];
}

// ---------------------------------------------------------------- helpers

const b64 = (text: string): string => Buffer.from(text, "utf8").toString("base64");
/** Base64 of `text` repeated `count` times, expanded by the runner so the fixture stays small. */
const repeatB64 = (text: string, count: number): Json => ({ $b64repeat: { text, count } });

const pub = (id: string, method: string, request: Json, extra?: Partial<GrpcStep>): GrpcStep => ({ id, grpc: { service: "Publisher", method, request }, ...extra });
const sub = (id: string, method: string, request: Json, extra?: Partial<GrpcStep>): GrpcStep => ({ id, grpc: { service: "Subscriber", method, request }, ...extra });
const sch = (id: string, method: string, request: Json, extra?: Partial<GrpcStep>): GrpcStep => ({ id, grpc: { service: "SchemaService", method, request }, ...extra });
const iam = (id: string, method: string, request: Json): GrpcStep => ({ id, grpc: { service: "IAMPolicy", method, request } });
const http = (id: string, method: string, path: string, body?: Json | string, note?: string): HttpStep => ({ id, http: { method, path, ...(body === undefined ? {} : { body }) }, ...(note === undefined ? {} : { note }) });
const sleep = (id: string, sleepMs: number, note?: string): SleepStep => ({ id, sleepMs, ...(note === undefined ? {} : { note }) });
const pushes = (id: string, atLeast: number, timeoutMs: number, note?: string): PushesStep => ({ id, pushes: { atLeast, timeoutMs }, ...(note === undefined ? {} : { note }) });
const pushStatus = (id: string, status: number): PushStatusStep => ({ id, pushStatus: status });

const topic = (id: string, name: string, extra: Json = {}): GrpcStep => pub(id, "createTopic", { name: `${T}/${name}`, ...(extra as object) });
const subscription = (id: string, name: string, topicName: string, extra: Json = {}): GrpcStep => sub(id, "createSubscription", { name: `${S}/${name}`, topic: `${T}/${topicName}`, ...(extra as object) });
const publish = (id: string, topicName: string, messages: Json[]): GrpcStep => pub(id, "publish", { topic: `${T}/${topicName}`, messages });
const pull = (id: string, name: string, maxMessages = 10, returnImmediately = true): GrpcStep =>
  sub(id, "pull", { subscription: `${S}/${name}`, maxMessages, ...(returnImmediately ? { returnImmediately: true } : {}) }, returnImmediately ? {} : { deadlineMs: 20_000 });
const ack = (id: string, name: string, ackIds: string[]): GrpcStep => sub(id, "acknowledge", { subscription: `${S}/${name}`, ackIds });
const modify = (id: string, name: string, ackIds: string[], ackDeadlineSeconds: number): GrpcStep => sub(id, "modifyAckDeadline", { subscription: `${S}/${name}`, ackIds, ackDeadlineSeconds });
const msg = (text: string, attributes?: Record<string, string>, orderingKey?: string): Json => ({ data: b64(text), ...(attributes ? { attributes } : {}), ...(orderingKey ? { orderingKey } : {}) });

const AVRO_RECORD = JSON.stringify({ type: "record", name: "Reading", fields: [{ name: "sensor", type: "string" }, { name: "value", type: "double" }] });
const AVRO_RECORD_V2 = JSON.stringify({ type: "record", name: "Reading", fields: [{ name: "sensor", type: "string" }, { name: "value", type: "double" }, { name: "unit", type: "string", default: "C" }] });

// ---------------------------------------------------------------- programs

export const PROGRAMS: readonly Program[] = [
  // ---------------------------------------------------------------- topics
  {
    id: "topic-names",
    category: "topics",
    title: "topic name validation on create, get and delete",
    steps: [
      topic("two-chars", "ab"),
      topic("three-chars", "abc"),
      topic("starts-with-digit", "1abc"),
      topic("starts-with-goog", "goog-topic"),
      topic("contains-goog", "my-goog-topic"),
      topic("uppercase-goog", "GoogTopic"),
      topic("allowed-chars", "Topic_1.two~three+four%five-six"),
      topic("invalid-char", "topic with space"),
      topic("invalid-slash", "topic/extra"),
      topic("max-length", `t${"x".repeat(254)}`),
      topic("too-long", `t${"x".repeat(255)}`),
      pub("empty-name", "createTopic", { name: "" }),
      pub("bare-name", "createTopic", { name: "just-a-name" }),
      pub("wrong-collection", "createTopic", { name: `${PROJECT}/subscriptions/not-a-topic` }),
      pub("no-project", "createTopic", { name: "projects//topics/abc" }),
      pub("get-invalid", "getTopic", { topic: "abc" }),
      pub("get-missing", "getTopic", { topic: `${T}/missing-topic` }),
      pub("delete-invalid", "deleteTopic", { topic: "abc" }),
      pub("delete-missing", "deleteTopic", { topic: `${T}/missing-topic` }),
      pub("list", "listTopics", { project: PROJECT }),
    ],
  },
  {
    id: "topic-crud",
    category: "topics",
    title: "topic create/get/list/update/delete over gRPC",
    steps: [
      topic("create-plain", "orders"),
      topic("create-labels", "events", { labels: { env: "test", team: "core" } }),
      topic("create-retention", "audit", { messageRetentionDuration: { seconds: "600" } }),
      topic("create-retention-short", "short-retention", { messageRetentionDuration: { seconds: "599" } }),
      topic("create-retention-long", "long-retention", { messageRetentionDuration: { seconds: "2678401" } }),
      topic("create-kms", "kms", { kmsKeyName: "projects/p/locations/l/keyRings/r/cryptoKeys/k" }),
      topic("create-policy", "policy", { messageStoragePolicy: { allowedPersistenceRegions: ["us-central1"] } }),
      topic("create-schema-missing", "with-schema", { schemaSettings: { schema: `${SCHEMA}/nope`, encoding: "JSON" } }),
      topic("create-duplicate", "orders"),
      pub("get", "getTopic", { topic: `${T}/events` }),
      pub("list-all", "listTopics", { project: PROJECT }),
      pub("list-page-1", "listTopics", { project: PROJECT, pageSize: 2 }),
      pub("list-page-2", "listTopics", { project: PROJECT, pageSize: 2, pageToken: `${T}/kms` }),
      pub("list-bad-token", "listTopics", { project: PROJECT, pageSize: 2, pageToken: "garbage" }),
      pub("list-page-size-zero", "listTopics", { project: PROJECT, pageSize: 0 }),
      pub("list-negative", "listTopics", { project: PROJECT, pageSize: -1 }),
      pub("list-other-project", "listTopics", { project: OTHER_PROJECT }),
      pub("list-bad-project", "listTopics", { project: "nope" }),
      pub("update-labels", "updateTopic", { topic: { name: `${T}/events`, labels: { env: "prod" } }, updateMask: { paths: ["labels"] } }),
      pub("update-retention", "updateTopic", { topic: { name: `${T}/events`, messageRetentionDuration: { seconds: "1200" } }, updateMask: { paths: ["message_retention_duration"] } }),
      pub("update-camel-mask", "updateTopic", { topic: { name: `${T}/events`, messageRetentionDuration: { seconds: "1200" } }, updateMask: { paths: ["messageRetentionDuration"] } }),
      pub("update-no-mask", "updateTopic", { topic: { name: `${T}/events`, messageRetentionDuration: { seconds: "1200" } } }),
      pub("update-empty-mask", "updateTopic", { topic: { name: `${T}/events` }, updateMask: { paths: [] } }),
      pub("update-missing", "updateTopic", { topic: { name: `${T}/missing-topic`, messageRetentionDuration: { seconds: "1200" } }, updateMask: { paths: ["message_retention_duration"] } }),
      pub("update-kms", "updateTopic", { topic: { name: `${T}/events`, kmsKeyName: "projects/p/locations/l/keyRings/r/cryptoKeys/k2" }, updateMask: { paths: ["kms_key_name"] } }),
      pub("update-policy", "updateTopic", { topic: { name: `${T}/events`, messageStoragePolicy: { allowedPersistenceRegions: ["europe-west1"] } }, updateMask: { paths: ["message_storage_policy"] } }),
      pub("get-after-update", "getTopic", { topic: `${T}/events` }),
      pub("delete", "deleteTopic", { topic: `${T}/orders` }),
      pub("delete-again", "deleteTopic", { topic: `${T}/orders` }),
      pub("get-deleted", "getTopic", { topic: `${T}/orders` }),
      pub("list-after-delete", "listTopics", { project: PROJECT }),
    ],
  },
  {
    id: "topic-crud-http",
    category: "topics",
    title: "topic create/get/list/update/delete over HTTP/JSON",
    steps: [
      http("put", "PUT", `/v1/${T}/orders`, {}),
      http("put-labels", "PUT", `/v1/${T}/events`, { labels: { env: "test" }, messageRetentionDuration: "600s" }),
      http("put-duplicate", "PUT", `/v1/${T}/orders`, {}),
      http("put-invalid-name", "PUT", `/v1/${T}/ab`, {}),
      http("put-no-body", "PUT", `/v1/${T}/nobody`),
      http("get", "GET", `/v1/${T}/events`),
      http("get-missing", "GET", `/v1/${T}/missing-topic`),
      http("list", "GET", `/v1/${T}`),
      http("list-page", "GET", `/v1/${T}?pageSize=1`),
      http("list-page-token", "GET", `/v1/${T}?pageSize=1&pageToken=${encodeURIComponent(`${T}/nobody`)}`),
      http("list-other-project", "GET", `/v1/${OTHER_PROJECT}/topics`),
      http("patch-retention", "PATCH", `/v1/${T}/events`, { topic: { name: `${T}/events`, messageRetentionDuration: "1200s" }, updateMask: "message_retention_duration" }),
      http("patch-labels", "PATCH", `/v1/${T}/events`, { topic: { name: `${T}/events`, labels: { env: "prod" } }, updateMask: "labels" }),
      http("patch-no-mask", "PATCH", `/v1/${T}/events`, { topic: { name: `${T}/events`, messageRetentionDuration: "1200s" } }),
      http("patch-query-mask", "PATCH", `/v1/${T}/events?updateMask=message_retention_duration`, { topic: { name: `${T}/events`, messageRetentionDuration: "1800s" } }),
      http("get-after-patch", "GET", `/v1/${T}/events`),
      http("delete", "DELETE", `/v1/${T}/orders`),
      http("delete-again", "DELETE", `/v1/${T}/orders`),
      http("delete-invalid", "DELETE", `/v1/${T}/ab`),
      http("list-after", "GET", `/v1/${T}`),
    ],
  },
  {
    id: "topic-children",
    category: "topics",
    title: "listTopicSubscriptions, listTopicSnapshots and detachSubscription",
    steps: [
      topic("topic", "orders"),
      pub("subscriptions-empty", "listTopicSubscriptions", { topic: `${T}/orders` }),
      pub("subscriptions-missing", "listTopicSubscriptions", { topic: `${T}/missing-topic` }),
      pub("snapshots-empty", "listTopicSnapshots", { topic: `${T}/orders` }),
      pub("snapshots-missing", "listTopicSnapshots", { topic: `${T}/missing-topic` }),
      subscription("sub-a", "sub-a", "orders"),
      subscription("sub-b", "sub-b", "orders"),
      subscription("sub-c", "sub-c", "orders"),
      sub("snap-a", "createSnapshot", { name: `${SNAP}/snap-a`, subscription: `${S}/sub-a` }),
      sub("snap-b", "createSnapshot", { name: `${SNAP}/snap-b`, subscription: `${S}/sub-b` }),
      pub("subscriptions", "listTopicSubscriptions", { topic: `${T}/orders` }),
      pub("subscriptions-page-1", "listTopicSubscriptions", { topic: `${T}/orders`, pageSize: 2 }),
      pub("subscriptions-page-2", "listTopicSubscriptions", { topic: `${T}/orders`, pageSize: 2, pageToken: `${S}/sub-c` }),
      pub("snapshots", "listTopicSnapshots", { topic: `${T}/orders` }),
      pub("snapshots-page-1", "listTopicSnapshots", { topic: `${T}/orders`, pageSize: 1 }),
      pub("snapshots-page-2", "listTopicSnapshots", { topic: `${T}/orders`, pageSize: 1, pageToken: `${SNAP}/snap-b` }),
      pub("detach", "detachSubscription", { subscription: `${S}/sub-a` }),
      pub("detach-missing", "detachSubscription", { subscription: `${S}/missing-sub` }),
      http("subscriptions-http", "GET", `/v1/${T}/orders/subscriptions`),
      http("snapshots-http", "GET", `/v1/${T}/orders/snapshots?pageSize=1`),
      http("detach-http", "POST", `/v1/${S}/sub-a:detach`, {}),
      sub("delete-sub-b", "deleteSubscription", { subscription: `${S}/sub-b` }),
      pub("subscriptions-after-delete", "listTopicSubscriptions", { topic: `${T}/orders` }),
      pub("snapshots-after-delete", "listTopicSnapshots", { topic: `${T}/orders` }, { note: "snapshots outlive their subscription" }),
    ],
  },
  // ---------------------------------------------------------------- publish
  {
    id: "publish-validation",
    category: "publish",
    title: "publish request validation and message id allocation",
    steps: [
      topic("topic", "orders"),
      pub("missing-topic", "publish", { topic: `${T}/missing-topic`, messages: [msg("x")] }),
      pub("invalid-topic", "publish", { topic: "orders", messages: [msg("x")] }),
      pub("no-messages", "publish", { topic: `${T}/orders`, messages: [] }),
      pub("empty-message", "publish", { topic: `${T}/orders`, messages: [{}] }),
      pub("empty-data-only", "publish", { topic: `${T}/orders`, messages: [{ data: "" }] }),
      pub("attributes-only", "publish", { topic: `${T}/orders`, messages: [{ attributes: { kind: "ping" } }] }),
      pub("ordering-key-only", "publish", { topic: `${T}/orders`, messages: [{ orderingKey: "k" }] }),
      pub("data-only", "publish", { topic: `${T}/orders`, messages: [msg("hello")] }),
      pub("batch", "publish", { topic: `${T}/orders`, messages: [msg("one"), msg("two", { n: "two" }), msg("three", { n: "three" }, "key-a")] }),
      pub("mixed-empty", "publish", { topic: `${T}/orders`, messages: [msg("ok"), {}] }, { note: "one empty message rejects the whole batch" }),
      pub("client-message-id", "publish", { topic: `${T}/orders`, messages: [{ data: b64("x"), messageId: "client-supplied" }] }, { note: "the server assigns ids regardless" }),
      pub("client-publish-time", "publish", { topic: `${T}/orders`, messages: [{ data: b64("x"), publishTime: { seconds: "1" } }] }),
      pub("many-attributes", "publish", { topic: `${T}/orders`, messages: [{ data: b64("x"), attributes: Object.fromEntries(Array.from({ length: 101 }, (_, index) => [`k${String(index)}`, "v"])) }] }),
      pub("long-attribute-key", "publish", { topic: `${T}/orders`, messages: [{ data: b64("x"), attributes: { ["k".repeat(257)]: "v" } }] }),
      pub("long-attribute-value", "publish", { topic: `${T}/orders`, messages: [{ data: b64("x"), attributes: { k: "v".repeat(1025) } }] }),
      pub("empty-attribute-key", "publish", { topic: `${T}/orders`, messages: [{ data: b64("x"), attributes: { "": "v" } }] }),
      pub("goog-attribute", "publish", { topic: `${T}/orders`, messages: [{ data: b64("x"), attributes: { googclient_x: "v" } }] }),
      pub("long-ordering-key", "publish", { topic: `${T}/orders`, messages: [{ data: b64("x"), orderingKey: "o".repeat(1025) }] }),
      pub("large-data", "publish", { topic: `${T}/orders`, messages: [{ data: repeatB64("d", 10_000_001) }] }, { note: "10 MB + 1 byte" }),
      pub("large-data-ok", "publish", { topic: `${T}/orders`, messages: [{ data: repeatB64("d", 1_000_000) }] }),
      pub("after-all", "publish", { topic: `${T}/orders`, messages: [msg("last")] }),
    ],
  },
  {
    id: "publish-http",
    category: "publish",
    title: "publish over HTTP/JSON including malformed bodies",
    steps: [
      http("put-topic", "PUT", `/v1/${T}/orders`, {}),
      http("publish", "POST", `/v1/${T}/orders:publish`, { messages: [{ data: b64("hello"), attributes: { k: "v" } }] }),
      http("publish-batch", "POST", `/v1/${T}/orders:publish`, { messages: [{ data: b64("one") }, { data: b64("two"), orderingKey: "k" }] }),
      http("publish-missing", "POST", `/v1/${T}/missing-topic:publish`, { messages: [{ data: b64("x") }] }),
      http("publish-empty", "POST", `/v1/${T}/orders:publish`, { messages: [] }),
      http("publish-no-body", "POST", `/v1/${T}/orders:publish`),
      http("publish-bad-base64", "POST", `/v1/${T}/orders:publish`, { messages: [{ data: "!!!not-base64" }] }),
      http("publish-bad-json", "POST", `/v1/${T}/orders:publish`, "{not json"),
      http("publish-unknown-field", "POST", `/v1/${T}/orders:publish`, { messages: [{ data: b64("x"), bogus: 1 }] }),
      http("publish-wrong-type", "POST", `/v1/${T}/orders:publish`, { messages: "nope" }),
      http("publish-snake-case", "POST", `/v1/${T}/orders:publish`, { messages: [{ data: b64("x"), ordering_key: "k" }] }, "proto JSON accepts snake_case"),
      http("publish-get", "GET", `/v1/${T}/orders:publish`),
      http("publish-attributes-only", "POST", `/v1/${T}/orders:publish`, { messages: [{ attributes: { a: "b" } }] }),
      http("publish-empty-message", "POST", `/v1/${T}/orders:publish`, { messages: [{}] }),
    ],
  },
  // ---------------------------------------------------------------- subscriptions
  {
    id: "subscription-create-validation",
    category: "subscriptions",
    title: "createSubscription names, bounds and policies",
    steps: [
      topic("topic", "orders"),
      topic("dead-letter-topic", "dead-letters"),
      subscription("defaults", "defaults", "orders"),
      subscription("duplicate", "defaults", "orders"),
      subscription("missing-topic", "no-topic", "missing-topic"),
      sub("invalid-topic-name", "createSubscription", { name: `${S}/bad-topic`, topic: "orders" }),
      sub("no-topic", "createSubscription", { name: `${S}/no-topic-field` }),
      sub("short-name", "createSubscription", { name: `${S}/ab`, topic: `${T}/orders` }),
      sub("goog-name", "createSubscription", { name: `${S}/goog-sub`, topic: `${T}/orders` }),
      sub("bare-name", "createSubscription", { name: "bare", topic: `${T}/orders` }),
      sub("other-project", "createSubscription", { name: `${OTHER_PROJECT}/subscriptions/cross`, topic: `${T}/orders` }, { note: "cross-project subscription" }),
      subscription("deadline-zero", "deadline-zero", "orders", { ackDeadlineSeconds: 0 }),
      subscription("deadline-nine", "deadline-nine", "orders", { ackDeadlineSeconds: 9 }),
      subscription("deadline-ten", "deadline-ten", "orders", { ackDeadlineSeconds: 10 }),
      subscription("deadline-max", "deadline-max", "orders", { ackDeadlineSeconds: 600 }),
      subscription("deadline-over", "deadline-over", "orders", { ackDeadlineSeconds: 601 }),
      subscription("deadline-negative", "deadline-negative", "orders", { ackDeadlineSeconds: -1 }),
      subscription("retention-short", "retention-short", "orders", { messageRetentionDuration: { seconds: "599" } }),
      subscription("retention-min", "retention-min", "orders", { messageRetentionDuration: { seconds: "600" } }),
      subscription("retention-long", "retention-long", "orders", { messageRetentionDuration: { seconds: "2678401" } }),
      subscription("retention-max", "retention-max", "orders", { messageRetentionDuration: { seconds: "2678400" } }),
      subscription("retain-acked", "retain-acked", "orders", { retainAckedMessages: true }),
      subscription("ordering", "ordering", "orders", { enableMessageOrdering: true }),
      subscription("exactly-once", "exactly-once", "orders", { enableExactlyOnceDelivery: true }),
      subscription("labels", "labelled", "orders", { labels: { env: "test" } }),
      subscription("detached", "detached", "orders", { detached: true }),
      subscription("expiration-ttl", "expiration-ttl", "orders", { expirationPolicy: { ttl: { seconds: "86400" } } }),
      subscription("expiration-never", "expiration-never", "orders", { expirationPolicy: {} }),
      subscription("expiration-short", "expiration-short", "orders", { expirationPolicy: { ttl: { seconds: "60" } } }),
      subscription("dead-letter", "dead-letter", "orders", { deadLetterPolicy: { deadLetterTopic: `${T}/dead-letters`, maxDeliveryAttempts: 5 } }),
      subscription("dead-letter-default-attempts", "dead-letter-default", "orders", { deadLetterPolicy: { deadLetterTopic: `${T}/dead-letters` } }),
      subscription("dead-letter-few-attempts", "dead-letter-few", "orders", { deadLetterPolicy: { deadLetterTopic: `${T}/dead-letters`, maxDeliveryAttempts: 4 } }),
      subscription("dead-letter-many-attempts", "dead-letter-many", "orders", { deadLetterPolicy: { deadLetterTopic: `${T}/dead-letters`, maxDeliveryAttempts: 101 } }),
      subscription("dead-letter-missing-topic", "dead-letter-missing", "orders", { deadLetterPolicy: { deadLetterTopic: `${T}/missing-topic`, maxDeliveryAttempts: 5 } }),
      subscription("dead-letter-same-topic", "dead-letter-same", "orders", { deadLetterPolicy: { deadLetterTopic: `${T}/orders`, maxDeliveryAttempts: 5 } }),
      subscription("retry-policy", "retry-policy", "orders", { retryPolicy: { minimumBackoff: { seconds: "1" }, maximumBackoff: { seconds: "60" } } }),
      subscription("retry-policy-inverted", "retry-inverted", "orders", { retryPolicy: { minimumBackoff: { seconds: "60" }, maximumBackoff: { seconds: "1" } } }),
      subscription("retry-policy-empty", "retry-empty", "orders", { retryPolicy: {} }),
      subscription("filter", "filtered", "orders", { filter: 'attributes.kind = "ping"' }),
      subscription("filter-invalid", "filter-invalid", "orders", { filter: "attributes.kind =" }),
      subscription("filter-unknown-function", "filter-unknown", "orders", { filter: 'nope(attributes.kind, "x")' }),
      subscription("push", "push", "orders", { pushConfig: { pushEndpoint: "{{pushOrigin}}/hook" } }),
      subscription("push-attributes", "push-attributes", "orders", { pushConfig: { pushEndpoint: "{{pushOrigin}}/hook", attributes: { "x-goog-version": "v1" } } }),
      subscription("push-oidc", "push-oidc", "orders", { pushConfig: { pushEndpoint: "{{pushOrigin}}/hook", oidcToken: { serviceAccountEmail: "svc@example.test", audience: "aud" } } }),
      subscription("push-invalid-endpoint", "push-invalid", "orders", { pushConfig: { pushEndpoint: "not a url" } }),
      subscription("push-attributes-only", "push-attributes-only", "orders", { pushConfig: { attributes: { "x-goog-version": "v1" } } }),
      subscription("everything", "everything", "orders", {
        ackDeadlineSeconds: 30,
        retainAckedMessages: true,
        messageRetentionDuration: { seconds: "3600" },
        labels: { a: "b" },
        enableMessageOrdering: true,
        expirationPolicy: { ttl: { seconds: "86400" } },
        filter: 'attributes.kind = "ping"',
        deadLetterPolicy: { deadLetterTopic: `${T}/dead-letters`, maxDeliveryAttempts: 7 },
        retryPolicy: { minimumBackoff: { seconds: "2" }, maximumBackoff: { seconds: "30" } },
        enableExactlyOnceDelivery: true,
      }),
      sub("get-everything", "getSubscription", { subscription: `${S}/everything` }),
      sub("get-missing", "getSubscription", { subscription: `${S}/missing-sub` }),
      sub("get-invalid", "getSubscription", { subscription: "everything" }),
      sub("list", "listSubscriptions", { project: PROJECT }),
      sub("list-page-1", "listSubscriptions", { project: PROJECT, pageSize: 3 }),
      sub("list-page-2", "listSubscriptions", { project: PROJECT, pageSize: 3, pageToken: `${S}/deadline-ten` }),
      sub("list-other-project", "listSubscriptions", { project: OTHER_PROJECT }),
      sub("list-bad-project", "listSubscriptions", { project: "nope" }),
    ],
  },
  {
    id: "subscription-crud-http",
    category: "subscriptions",
    title: "subscription create/get/list/update/delete over HTTP/JSON",
    steps: [
      http("put-topic", "PUT", `/v1/${T}/orders`, {}),
      http("put", "PUT", `/v1/${S}/sub-a`, { topic: `${T}/orders`, ackDeadlineSeconds: 20, filter: 'attributes.x = "y"' }),
      http("put-duplicate", "PUT", `/v1/${S}/sub-a`, { topic: `${T}/orders` }),
      http("put-missing-topic", "PUT", `/v1/${S}/sub-b`, { topic: `${T}/missing-topic` }),
      http("put-no-topic", "PUT", `/v1/${S}/sub-b`, {}),
      http("put-durations", "PUT", `/v1/${S}/sub-c`, { topic: `${T}/orders`, messageRetentionDuration: "3600s", expirationPolicy: { ttl: "86400s" }, retryPolicy: { minimumBackoff: "1s", maximumBackoff: "2.5s" } }),
      http("put-bad-duration", "PUT", `/v1/${S}/sub-d`, { topic: `${T}/orders`, messageRetentionDuration: "soon" }),
      http("get", "GET", `/v1/${S}/sub-a`),
      http("get-missing", "GET", `/v1/${S}/missing-sub`),
      http("list", "GET", `/v1/${S}`),
      http("list-page", "GET", `/v1/${S}?pageSize=1`),
      http("patch-deadline", "PATCH", `/v1/${S}/sub-a`, { subscription: { name: `${S}/sub-a`, ackDeadlineSeconds: 30 }, updateMask: "ack_deadline_seconds" }),
      http("patch-camel", "PATCH", `/v1/${S}/sub-a`, { subscription: { name: `${S}/sub-a`, ackDeadlineSeconds: 40 }, updateMask: "ackDeadlineSeconds" }),
      http("patch-push", "PATCH", `/v1/${S}/sub-a?updateMask=push_config`, { subscription: { name: `${S}/sub-a`, pushConfig: { pushEndpoint: "{{pushOrigin}}/hook" } } }),
      http("get-after-patch", "GET", `/v1/${S}/sub-a`),
      http("modify-push-config", "POST", `/v1/${S}/sub-a:modifyPushConfig`, { pushConfig: {} }),
      http("get-after-modify", "GET", `/v1/${S}/sub-a`),
      http("delete", "DELETE", `/v1/${S}/sub-a`),
      http("delete-again", "DELETE", `/v1/${S}/sub-a`),
      http("list-after", "GET", `/v1/${S}`),
    ],
  },
  {
    id: "subscription-update",
    category: "subscriptions",
    title: "updateSubscription masks and modifyPushConfig",
    steps: [
      topic("topic", "orders"),
      topic("other-topic", "other"),
      topic("dead-letter-topic", "dead-letters"),
      subscription("sub", "sub-a", "orders"),
      sub("no-mask", "updateSubscription", { subscription: { name: `${S}/sub-a`, ackDeadlineSeconds: 20 } }),
      sub("empty-mask", "updateSubscription", { subscription: { name: `${S}/sub-a`, ackDeadlineSeconds: 20 }, updateMask: { paths: [] } }),
      sub("ack-deadline", "updateSubscription", { subscription: { name: `${S}/sub-a`, ackDeadlineSeconds: 20 }, updateMask: { paths: ["ack_deadline_seconds"] } }),
      sub("ack-deadline-out-of-bounds", "updateSubscription", { subscription: { name: `${S}/sub-a`, ackDeadlineSeconds: 601 }, updateMask: { paths: ["ack_deadline_seconds"] } }),
      sub("camel-mask", "updateSubscription", { subscription: { name: `${S}/sub-a`, ackDeadlineSeconds: 25 }, updateMask: { paths: ["ackDeadlineSeconds"] } }),
      sub("unknown-field", "updateSubscription", { subscription: { name: `${S}/sub-a` }, updateMask: { paths: ["bogus"] } }),
      sub("labels", "updateSubscription", { subscription: { name: `${S}/sub-a`, labels: { a: "b" } }, updateMask: { paths: ["labels"] } }),
      sub("topic-field", "updateSubscription", { subscription: { name: `${S}/sub-a`, topic: `${T}/other` }, updateMask: { paths: ["topic"] } }),
      sub("push-config", "updateSubscription", { subscription: { name: `${S}/sub-a`, pushConfig: { pushEndpoint: "{{pushOrigin}}/hook", attributes: { "x-goog-version": "v1" } } }, updateMask: { paths: ["push_config"] } }),
      sub("push-config-clear", "updateSubscription", { subscription: { name: `${S}/sub-a`, pushConfig: {} }, updateMask: { paths: ["push_config"] } }),
      sub("retain-acked", "updateSubscription", { subscription: { name: `${S}/sub-a`, retainAckedMessages: true }, updateMask: { paths: ["retain_acked_messages"] } }),
      sub("retention", "updateSubscription", { subscription: { name: `${S}/sub-a`, messageRetentionDuration: { seconds: "3600" } }, updateMask: { paths: ["message_retention_duration"] } }),
      sub("retention-out-of-bounds", "updateSubscription", { subscription: { name: `${S}/sub-a`, messageRetentionDuration: { seconds: "1" } }, updateMask: { paths: ["message_retention_duration"] } }),
      sub("ordering", "updateSubscription", { subscription: { name: `${S}/sub-a`, enableMessageOrdering: true }, updateMask: { paths: ["enable_message_ordering"] } }),
      sub("filter", "updateSubscription", { subscription: { name: `${S}/sub-a`, filter: 'attributes.a = "b"' }, updateMask: { paths: ["filter"] } }),
      sub("expiration", "updateSubscription", { subscription: { name: `${S}/sub-a`, expirationPolicy: { ttl: { seconds: "86400" } } }, updateMask: { paths: ["expiration_policy"] } }),
      sub("dead-letter", "updateSubscription", { subscription: { name: `${S}/sub-a`, deadLetterPolicy: { deadLetterTopic: `${T}/dead-letters`, maxDeliveryAttempts: 6 } }, updateMask: { paths: ["dead_letter_policy"] } }),
      sub("retry", "updateSubscription", { subscription: { name: `${S}/sub-a`, retryPolicy: { minimumBackoff: { seconds: "3" }, maximumBackoff: { seconds: "9" } } }, updateMask: { paths: ["retry_policy"] } }),
      sub("exactly-once", "updateSubscription", { subscription: { name: `${S}/sub-a`, enableExactlyOnceDelivery: true }, updateMask: { paths: ["enable_exactly_once_delivery"] } }),
      sub("detached", "updateSubscription", { subscription: { name: `${S}/sub-a`, detached: true }, updateMask: { paths: ["detached"] } }),
      sub("multiple", "updateSubscription", { subscription: { name: `${S}/sub-a`, ackDeadlineSeconds: 45, retainAckedMessages: false }, updateMask: { paths: ["ack_deadline_seconds", "retain_acked_messages"] } }),
      sub("missing", "updateSubscription", { subscription: { name: `${S}/missing-sub`, ackDeadlineSeconds: 45 }, updateMask: { paths: ["ack_deadline_seconds"] } }),
      sub("get", "getSubscription", { subscription: `${S}/sub-a` }),
      sub("modify-push", "modifyPushConfig", { subscription: `${S}/sub-a`, pushConfig: { pushEndpoint: "{{pushOrigin}}/hook2" } }),
      sub("modify-push-oidc", "modifyPushConfig", { subscription: `${S}/sub-a`, pushConfig: { pushEndpoint: "{{pushOrigin}}/hook3", oidcToken: { serviceAccountEmail: "svc@example.test", audience: "aud" } } }),
      sub("get-after-modify", "getSubscription", { subscription: `${S}/sub-a` }),
      sub("modify-push-clear", "modifyPushConfig", { subscription: `${S}/sub-a`, pushConfig: {} }),
      sub("modify-push-missing", "modifyPushConfig", { subscription: `${S}/missing-sub`, pushConfig: {} }),
      sub("modify-push-no-config", "modifyPushConfig", { subscription: `${S}/sub-a` }),
      sub("get-final", "getSubscription", { subscription: `${S}/sub-a` }),
    ],
  },
  {
    id: "subscription-topic-lifecycle",
    category: "subscriptions",
    title: "a deleted topic leaves _deleted-topic_ subscriptions behind",
    steps: [
      topic("topic", "orders"),
      subscription("sub", "sub-a", "orders"),
      publish("publish", "orders", [msg("before-delete")]),
      pub("delete-topic", "deleteTopic", { topic: `${T}/orders` }),
      sub("get", "getSubscription", { subscription: `${S}/sub-a` }),
      sub("list", "listSubscriptions", { project: PROJECT }),
      pull("pull", "sub-a"),
      publish("publish-after", "orders", [msg("after-delete")]),
      topic("recreate", "orders"),
      publish("publish-recreated", "orders", [msg("after-recreate")]),
      pull("pull-recreated", "sub-a"),
      sub("get-recreated", "getSubscription", { subscription: `${S}/sub-a` }),
      pub("children", "listTopicSubscriptions", { topic: `${T}/orders` }),
      sub("delete-sub", "deleteSubscription", { subscription: `${S}/sub-a` }),
      sub("delete-sub-again", "deleteSubscription", { subscription: `${S}/sub-a` }),
      sub("delete-invalid", "deleteSubscription", { subscription: "sub-a" }),
      sub("list-after", "listSubscriptions", { project: PROJECT }),
    ],
  },
  // ---------------------------------------------------------------- pull and ack
  {
    id: "pull-ack",
    category: "pull",
    title: "pull, acknowledge and modifyAckDeadline over gRPC",
    steps: [
      topic("topic", "orders"),
      subscription("sub", "sub-a", "orders"),
      sub("pull-no-max", "pull", { subscription: `${S}/sub-a`, returnImmediately: true }),
      sub("pull-zero-max", "pull", { subscription: `${S}/sub-a`, maxMessages: 0, returnImmediately: true }),
      sub("pull-negative-max", "pull", { subscription: `${S}/sub-a`, maxMessages: -1, returnImmediately: true }),
      pull("pull-missing", "missing-sub"),
      sub("pull-invalid", "pull", { subscription: "sub-a", maxMessages: 1, returnImmediately: true }),
      pull("pull-empty", "sub-a"),
      publish("publish", "orders", [msg("one", { n: "one" }), msg("two"), msg("three")]),
      pull("pull-two", "sub-a", 2),
      pull("pull-rest", "sub-a", 10),
      pull("pull-outstanding", "sub-a", 10),
      ack("ack-one", "sub-a", ["{{ackId:pull-two}}"]),
      ack("ack-again", "sub-a", ["{{ackId:pull-two}}"]),
      ack("ack-unknown", "sub-a", [`${S}/sub-a:999`]),
      ack("ack-garbage", "sub-a", ["garbage"]),
      ack("ack-empty", "sub-a", []),
      ack("ack-missing-sub", "missing-sub", ["x"]),
      sub("ack-other-subscription-id", "acknowledge", { subscription: `${S}/sub-a`, ackIds: [`${S}/other-sub:1`] }),
      modify("extend", "sub-a", ["{{ackId:pull-two#2}}"], 600),
      modify("extend-over", "sub-a", ["{{ackId:pull-two#2}}"], 601),
      modify("extend-negative", "sub-a", ["{{ackId:pull-two#2}}"], -1),
      modify("modify-empty", "sub-a", [], 10),
      modify("modify-garbage", "sub-a", ["garbage"], 10),
      modify("modify-missing-sub", "missing-sub", ["x"], 10),
      modify("nack", "sub-a", ["{{ackId:pull-rest}}"], 0),
      pull("pull-after-nack", "sub-a"),
      modify("nack-acked", "sub-a", ["{{ackId:pull-two}}"], 0),
      pull("pull-after-nack-acked", "sub-a"),
      publish("publish-more", "orders", [msg("four"), msg("five")]),
      pull("pull-blocking", "sub-a", 1, false),
      pull("pull-one-more", "sub-a", 1),
      pull("pull-none-left", "sub-a", 5),
    ],
  },
  {
    id: "pull-ack-http",
    category: "pull",
    title: "pull, acknowledge and modifyAckDeadline over HTTP/JSON",
    steps: [
      http("put-topic", "PUT", `/v1/${T}/orders`, {}),
      http("put-sub", "PUT", `/v1/${S}/sub-a`, { topic: `${T}/orders` }),
      http("pull-empty", "POST", `/v1/${S}/sub-a:pull`, { maxMessages: 5, returnImmediately: true }),
      http("pull-no-max", "POST", `/v1/${S}/sub-a:pull`, { returnImmediately: true }),
      http("pull-missing", "POST", `/v1/${S}/missing-sub:pull`, { maxMessages: 5 }),
      http("publish", "POST", `/v1/${T}/orders:publish`, { messages: [{ data: b64("one"), attributes: { n: "one" } }, { data: b64("two") }] }),
      http("pull", "POST", `/v1/${S}/sub-a:pull`, { maxMessages: 5 }),
      http("modify", "POST", `/v1/${S}/sub-a:modifyAckDeadline`, { ackIds: ["{{ackId:pull}}"], ackDeadlineSeconds: 0 }),
      http("pull-after-nack", "POST", `/v1/${S}/sub-a:pull`, { maxMessages: 5, returnImmediately: true }),
      http("ack", "POST", `/v1/${S}/sub-a:acknowledge`, { ackIds: ["{{ackId:pull}}", "{{ackId:pull#2}}", "{{ackId:pull-after-nack}}"] }),
      http("ack-empty", "POST", `/v1/${S}/sub-a:acknowledge`, { ackIds: [] }),
      http("ack-garbage", "POST", `/v1/${S}/sub-a:acknowledge`, { ackIds: ["garbage"] }),
      http("ack-no-body", "POST", `/v1/${S}/sub-a:acknowledge`),
      http("modify-over", "POST", `/v1/${S}/sub-a:modifyAckDeadline`, { ackIds: ["{{ackId:pull}}"], ackDeadlineSeconds: 601 }),
      http("pull-none", "POST", `/v1/${S}/sub-a:pull`, { maxMessages: 5, returnImmediately: true }),
    ],
  },
  {
    id: "pull-batches",
    category: "pull",
    title: "maxMessages batching across a larger backlog",
    steps: [
      topic("topic", "orders"),
      subscription("sub", "sub-a", "orders"),
      publish("publish-a", "orders", Array.from({ length: 12 }, (_, index) => msg(`m${String(index + 1)}`))),
      publish("publish-b", "orders", Array.from({ length: 8 }, (_, index) => msg(`n${String(index + 1)}`))),
      pull("pull-5-a", "sub-a", 5),
      pull("pull-5-b", "sub-a", 5),
      pull("pull-5-c", "sub-a", 5),
      pull("pull-5-d", "sub-a", 5),
      pull("pull-5-e", "sub-a", 5),
      pull("pull-1000", "sub-a", 1000),
      ack("ack-all", "sub-a", ["{{ackId:pull-5-a}}", "{{ackId:pull-5-a#2}}", "{{ackId:pull-5-a#3}}", "{{ackId:pull-5-a#4}}", "{{ackId:pull-5-a#5}}", "{{ackId:pull-5-b}}", "{{ackId:pull-5-b#2}}", "{{ackId:pull-5-b#3}}", "{{ackId:pull-5-b#4}}", "{{ackId:pull-5-b#5}}"]),
      modify("nack-rest", "sub-a", ["{{ackId:pull-5-c}}", "{{ackId:pull-5-c#2}}", "{{ackId:pull-5-c#3}}", "{{ackId:pull-5-c#4}}", "{{ackId:pull-5-c#5}}", "{{ackId:pull-5-d}}", "{{ackId:pull-5-d#2}}", "{{ackId:pull-5-d#3}}", "{{ackId:pull-5-d#4}}", "{{ackId:pull-5-d#5}}"], 0),
      pull("pull-redelivered", "sub-a", 1000),
    ],
  },
  {
    id: "ack-deadline-expiry",
    category: "pull",
    title: "an unacknowledged message is redelivered after its ack deadline",
    steps: [
      topic("topic", "orders"),
      subscription("sub", "sub-a", "orders", { ackDeadlineSeconds: 10 }),
      publish("publish", "orders", [msg("expiring")]),
      pull("pull", "sub-a", 5),
      pull("pull-leased", "sub-a", 5),
      sleep("wait-past-deadline", 10_500),
      pull("pull-redelivered", "sub-a", 5),
      modify("extend", "sub-a", ["{{ackId:pull-redelivered}}"], 20),
      sleep("wait-inside-extension", 10_500),
      pull("pull-still-leased", "sub-a", 5),
      ack("ack-expired-id", "sub-a", ["{{ackId:pull}}"]),
      pull("pull-after-stale-ack", "sub-a", 5),
      ack("ack-current", "sub-a", ["{{ackId:pull-redelivered}}"]),
      sleep("wait-after-ack", 10_500),
      pull("pull-after-ack", "sub-a", 5),
    ],
  },
  {
    id: "blocking-pull",
    category: "pull",
    title: "pull without returnImmediately waits for redelivery",
    steps: [
      topic("topic", "orders"),
      subscription("sub", "sub-a", "orders", { ackDeadlineSeconds: 10 }),
      publish("publish", "orders", [msg("one")]),
      pull("pull", "sub-a", 5),
      pull("pull-blocks-until-redelivery", "sub-a", 5, false),
      ack("ack", "sub-a", ["{{ackId:pull-blocks-until-redelivery}}"]),
      { ...pull("pull-times-out", "sub-a", 5, false), deadlineMs: 3000, note: "the client deadline expires before the emulator's long poll" },
    ],
  },
  {
    id: "dead-letter",
    category: "pull",
    title: "deliveryAttempt and dead-letter forwarding after maxDeliveryAttempts",
    steps: [
      topic("topic", "orders"),
      topic("dead-letter-topic", "dead-letters"),
      subscription("dlq-sub", "dlq-sub", "dead-letters"),
      subscription("sub", "sub-a", "orders", { deadLetterPolicy: { deadLetterTopic: `${T}/dead-letters`, maxDeliveryAttempts: 5 } }),
      subscription("plain-sub", "plain", "orders"),
      publish("publish", "orders", [msg("poison")]),
      pull("attempt-1", "sub-a", 5),
      modify("nack-1", "sub-a", ["{{ackId:attempt-1}}"], 0),
      pull("attempt-2", "sub-a", 5),
      modify("nack-2", "sub-a", ["{{ackId:attempt-2}}"], 0),
      pull("attempt-3", "sub-a", 5),
      modify("nack-3", "sub-a", ["{{ackId:attempt-3}}"], 0),
      pull("attempt-4", "sub-a", 5),
      modify("nack-4", "sub-a", ["{{ackId:attempt-4}}"], 0),
      pull("attempt-5", "sub-a", 5),
      modify("nack-5", "sub-a", ["{{ackId:attempt-5}}"], 0),
      pull("attempt-6", "sub-a", 5),
      sleep("settle", 500),
      pull("dead-letters", "dlq-sub", 5),
      pull("plain", "plain", 5, true),
    ],
  },
  {
    id: "retained-acked-and-seek-time",
    category: "seek",
    title: "retainAckedMessages, seek to a time and seek to the future",
    steps: [
      topic("topic", "orders"),
      subscription("retaining", "retaining", "orders", { retainAckedMessages: true }),
      subscription("plain", "plain", "orders"),
      publish("publish-1", "orders", [msg("first")]),
      sleep("gap", 1100),
      publish("publish-2", "orders", [msg("second")]),
      pull("pull-retaining", "retaining", 5),
      ack("ack-retaining", "retaining", ["{{ackId:pull-retaining}}", "{{ackId:pull-retaining#2}}"]),
      pull("pull-plain", "plain", 5),
      ack("ack-plain", "plain", ["{{ackId:pull-plain}}", "{{ackId:pull-plain#2}}"]),
      sub("seek-retaining-epoch", "seek", { subscription: `${S}/retaining`, time: { seconds: "0" } }),
      pull("pull-retaining-after-seek", "retaining", 5),
      sub("seek-plain-epoch", "seek", { subscription: `${S}/plain`, time: { seconds: "0" } }),
      pull("pull-plain-after-seek", "plain", 5),
      sub("seek-retaining-between", "seek", { subscription: `${S}/retaining`, time: "{{timeBetween:publish-1:publish-2}}" }),
      pull("pull-retaining-between", "retaining", 5),
      sub("seek-future", "seek", { subscription: `${S}/retaining`, time: { seconds: "4102444800" } }),
      pull("pull-retaining-future", "retaining", 5),
      sub("seek-none", "seek", { subscription: `${S}/retaining` }),
      sub("seek-both", "seek", { subscription: `${S}/retaining`, time: { seconds: "0" }, snapshot: `${SNAP}/none` }),
      sub("seek-missing", "seek", { subscription: `${S}/missing-sub`, time: { seconds: "0" } }),
      http("seek-http", "POST", `/v1/${S}/retaining:seek`, { time: "1970-01-01T00:00:00Z" }),
      http("pull-http-after-seek", "POST", `/v1/${S}/retaining:pull`, { maxMessages: 5, returnImmediately: true }),
    ],
  },
  {
    id: "snapshots",
    category: "seek",
    title: "snapshot create/get/list/delete and seek to a snapshot",
    steps: [
      topic("topic", "orders"),
      subscription("sub", "sub-a", "orders"),
      publish("publish-1", "orders", [msg("one")]),
      sub("create", "createSnapshot", { name: `${SNAP}/snap-a`, subscription: `${S}/sub-a`, labels: { k: "v" } }),
      sub("create-duplicate", "createSnapshot", { name: `${SNAP}/snap-a`, subscription: `${S}/sub-a` }),
      sub("create-missing-sub", "createSnapshot", { name: `${SNAP}/snap-b`, subscription: `${S}/missing-sub` }),
      sub("create-invalid-name", "createSnapshot", { name: "snap", subscription: `${S}/sub-a` }),
      sub("create-short-name", "createSnapshot", { name: `${SNAP}/ab`, subscription: `${S}/sub-a` }),
      sub("create-no-sub", "createSnapshot", { name: `${SNAP}/snap-c` }),
      sub("get", "getSnapshot", { snapshot: `${SNAP}/snap-a` }),
      sub("get-missing", "getSnapshot", { snapshot: `${SNAP}/missing-snap` }),
      sub("get-invalid", "getSnapshot", { snapshot: "snap-a" }),
      sub("list", "listSnapshots", { project: PROJECT }),
      sub("list-other-project", "listSnapshots", { project: OTHER_PROJECT }),
      pull("pull-1", "sub-a", 5),
      ack("ack-1", "sub-a", ["{{ackId:pull-1}}"]),
      publish("publish-2", "orders", [msg("two")]),
      pull("pull-2", "sub-a", 5),
      ack("ack-2", "sub-a", ["{{ackId:pull-2}}"]),
      pull("pull-empty", "sub-a", 5),
      sub("seek", "seek", { subscription: `${S}/sub-a`, snapshot: `${SNAP}/snap-a` }),
      pull("pull-after-seek", "sub-a", 5),
      sub("seek-missing-snapshot", "seek", { subscription: `${S}/sub-a`, snapshot: `${SNAP}/missing-snap` }),
      sub("create-second", "createSnapshot", { name: `${SNAP}/snap-b`, subscription: `${S}/sub-a` }),
      sub("list-page-1", "listSnapshots", { project: PROJECT, pageSize: 1 }),
      sub("list-page-2", "listSnapshots", { project: PROJECT, pageSize: 1, pageToken: `${SNAP}/snap-b` }),
      sub("update", "updateSnapshot", { snapshot: { name: `${SNAP}/snap-a`, labels: { k: "w" } }, updateMask: { paths: ["labels"] } }),
      sub("delete", "deleteSnapshot", { snapshot: `${SNAP}/snap-a` }),
      sub("delete-again", "deleteSnapshot", { snapshot: `${SNAP}/snap-a` }),
      sub("seek-deleted", "seek", { subscription: `${S}/sub-a`, snapshot: `${SNAP}/snap-a` }),
      sub("delete-sub", "deleteSubscription", { subscription: `${S}/sub-a` }),
      sub("get-after-sub-delete", "getSnapshot", { snapshot: `${SNAP}/snap-b` }),
      subscription("sub-again", "sub-b", "orders"),
      sub("seek-other-sub", "seek", { subscription: `${S}/sub-b`, snapshot: `${SNAP}/snap-b` }),
      pull("pull-sub-b", "sub-b", 5),
      http("put-http", "PUT", `/v1/${SNAP}/snap-http`, { subscription: `${S}/sub-b` }),
      http("get-http", "GET", `/v1/${SNAP}/snap-http`),
      http("list-http", "GET", `/v1/${SNAP}`),
      http("seek-http", "POST", `/v1/${S}/sub-b:seek`, { snapshot: `${SNAP}/snap-http` }),
      http("patch-http", "PATCH", `/v1/${SNAP}/snap-http`, { snapshot: { name: `${SNAP}/snap-http`, labels: { a: "b" } }, updateMask: "labels" }),
      http("delete-http", "DELETE", `/v1/${SNAP}/snap-http`),
      http("get-http-deleted", "GET", `/v1/${SNAP}/snap-http`),
    ],
  },
  // ---------------------------------------------------------------- ordering and filters
  {
    id: "ordering-keys",
    category: "ordering",
    title: "ordering keys: one key delivers in order and blocks on its outstanding message; the unordered mirror",
    steps: [
      topic("topic", "orders"),
      topic("single-topic", "single-key"),
      subscription("ordered", "ordered", "orders", { enableMessageOrdering: true }),
      subscription("unordered", "unordered", "orders"),
      subscription("single", "single", "single-key", { enableMessageOrdering: true }),
      publish("publish", "orders", [msg("a1", undefined, "a"), msg("b1", undefined, "b"), msg("a2", undefined, "a"), msg("c1"), msg("b2", undefined, "b"), msg("a3", undefined, "a")]),
      { ...pull("pull-ordered", "ordered", 10), sortReceived: true, note: "the set of messages an ordered subscription delivers at once; the official emulator interleaves keys differently from run to run" },
      pull("pull-unordered", "unordered", 10),
      ack("ack-ordered", "ordered", ["{{ackId:pull-ordered}}", "{{ackId:pull-ordered#2}}", "{{ackId:pull-ordered#3}}", "{{ackId:pull-ordered#4}}", "{{ackId:pull-ordered#5}}", "{{ackId:pull-ordered#6}}"]),
      pull("pull-ordered-drained", "ordered", 10),
      publish("publish-more", "orders", [msg("a4", undefined, "a"), msg("b3", undefined, "b")]),
      { ...pull("pull-more", "ordered", 10), sortReceived: true },
      pull("pull-unordered-more", "unordered", 10),
      publish("publish-single-key", "single-key", [msg("d1", undefined, "d"), msg("d2", undefined, "d"), msg("d3", undefined, "d")]),
      pull("pull-max-one", "single", 1),
      pull("pull-max-one-again", "single", 1),
      ack("ack-first-single", "single", ["{{ackId:pull-max-one}}"]),
      pull("pull-max-one-after-ack", "single", 1),
      pull("pull-single-rest", "single", 10),
      modify("nack-second-single", "single", ["{{ackId:pull-max-one-after-ack}}"], 0),
      pull("pull-single-after-nack", "single", 10),
      ack("ack-second-single", "single", ["{{ackId:pull-single-after-nack}}"]),
      pull("pull-single-third", "single", 10),
    ],
  },
  {
    id: "filters",
    category: "filters",
    title: "attribute filters: equality, existence, hasPrefix, NOT/AND/OR",
    steps: [
      topic("topic", "orders"),
      subscription("equality", "equality", "orders", { filter: 'attributes.kind = "ping"' }),
      subscription("inequality", "inequality", "orders", { filter: 'attributes.kind != "ping"' }),
      subscription("existence", "existence", "orders", { filter: "attributes:kind" }),
      subscription("prefix", "prefix", "orders", { filter: 'hasPrefix(attributes.kind, "pi")' }),
      subscription("not", "negated", "orders", { filter: 'NOT attributes.kind = "ping"' }),
      subscription("and", "conjunction", "orders", { filter: 'attributes.kind = "ping" AND attributes.priority = "high"' }),
      subscription("or", "disjunction", "orders", { filter: 'attributes.kind = "pong" OR attributes.priority = "high"' }),
      subscription("parentheses", "parenthesised", "orders", { filter: '(attributes.kind = "ping" OR attributes.kind = "pong") AND NOT attributes:priority' }),
      subscription("unfiltered", "unfiltered", "orders"),
      subscription("invalid", "invalid", "orders", { filter: "attributes.kind =" }),
      subscription("unknown-function", "unknown-function", "orders", { filter: 'nope(attributes.kind, "x")' }),
      subscription("data-filter", "data-filter", "orders", { filter: 'data = "x"' }),
      subscription("ordering-key-filter", "ordering-key-filter", "orders", { filter: 'orderingKey = "k"' }),
      publish("publish", "orders", [
        msg("m1", { kind: "ping" }),
        msg("m2", { kind: "pong" }),
        msg("m3", { kind: "ping", priority: "high" }),
        msg("m4", { priority: "high" }),
        msg("m5"),
        msg("m6", { kind: "pizza" }),
      ]),
      pull("pull-equality", "equality", 10),
      pull("pull-inequality", "inequality", 10),
      pull("pull-existence", "existence", 10),
      pull("pull-prefix", "prefix", 10),
      pull("pull-not", "negated", 10),
      pull("pull-and", "conjunction", 10),
      pull("pull-or", "disjunction", 10),
      pull("pull-parentheses", "parenthesised", 10),
      pull("pull-unfiltered", "unfiltered", 10),
      sub("update-filter", "updateSubscription", { subscription: { name: `${S}/equality`, filter: 'attributes.kind = "pong"' }, updateMask: { paths: ["filter"] } }),
      sub("get-equality", "getSubscription", { subscription: `${S}/equality` }),
    ],
  },
  // ---------------------------------------------------------------- streaming pull
  {
    id: "streaming-pull",
    category: "streaming",
    title: "streamingPull delivery, in-stream ack and modifyAckDeadline",
    steps: [
      topic("topic", "orders"),
      subscription("sub", "sub-a", "orders", { ackDeadlineSeconds: 10 }),
      publish("publish", "orders", [msg("one"), msg("two"), msg("three")]),
      {
        id: "stream",
        stream: {
          service: "Subscriber",
          method: "streamingPull",
          actions: [
            { write: { subscription: `${S}/sub-a`, streamAckDeadlineSeconds: 10, clientId: "client-1", maxOutstandingMessages: "100", maxOutstandingBytes: "1000000" } },
            { waitMs: 700 },
            { write: { ackIds: ["{{ackId:stream}}"], modifyDeadlineAckIds: ["{{ackId:stream#2}}"], modifyDeadlineSeconds: [0] } },
            { waitMs: 700 },
            { end: true },
          ],
        },
      },
      pull("pull-after-stream", "sub-a", 10),
      {
        id: "stream-missing",
        stream: { service: "Subscriber", method: "streamingPull", actions: [{ write: { subscription: `${S}/missing-sub`, streamAckDeadlineSeconds: 10 } }, { waitMs: 500 }, { end: true }] },
      },
      {
        id: "stream-no-subscription",
        stream: { service: "Subscriber", method: "streamingPull", actions: [{ write: { streamAckDeadlineSeconds: 10 } }, { waitMs: 500 }, { end: true }] },
      },
      {
        id: "stream-bad-deadline",
        stream: { service: "Subscriber", method: "streamingPull", actions: [{ write: { subscription: `${S}/sub-a`, streamAckDeadlineSeconds: 5 } }, { waitMs: 500 }, { end: true }] },
      },
      {
        id: "stream-invalid-name",
        stream: { service: "Subscriber", method: "streamingPull", actions: [{ write: { subscription: "sub-a", streamAckDeadlineSeconds: 10 } }, { waitMs: 500 }, { end: true }] },
      },
    ],
  },
  {
    id: "streaming-pull-redelivery",
    category: "streaming",
    title: "messages outstanding on a closed stream and delivery to a live stream",
    steps: [
      topic("topic", "orders"),
      subscription("sub", "sub-a", "orders", { ackDeadlineSeconds: 10 }),
      publish("publish", "orders", [msg("one")]),
      {
        id: "stream-then-close",
        stream: { service: "Subscriber", method: "streamingPull", actions: [{ write: { subscription: `${S}/sub-a`, streamAckDeadlineSeconds: 10 } }, { waitMs: 700 }, { cancel: true }] },
      },
      pull("pull-right-after-close", "sub-a", 10),
      sleep("wait-past-deadline", 10_500),
      pull("pull-after-deadline", "sub-a", 10),
      modify("nack", "sub-a", ["{{ackId:pull-after-deadline}}"], 0),
      {
        id: "stream-live-publish",
        stream: {
          service: "Subscriber",
          method: "streamingPull",
          actions: [
            { write: { subscription: `${S}/sub-a`, streamAckDeadlineSeconds: 10 } },
            { waitMs: 700 },
            { write: { ackIds: ["{{ackId:stream-live-publish}}"] } },
            { waitMs: 300 },
            { end: true },
          ],
        },
      },
      pull("pull-drained", "sub-a", 10),
    ],
  },
  {
    id: "streaming-pull-ordering",
    category: "streaming",
    title: "one ordering key over streamingPull",
    steps: [
      topic("topic", "orders"),
      subscription("sub", "ordered", "orders", { enableMessageOrdering: true, ackDeadlineSeconds: 10 }),
      publish("publish", "orders", [msg("a1", undefined, "a"), msg("a2", undefined, "a"), msg("a3", undefined, "a")]),
      {
        id: "stream",
        stream: {
          service: "Subscriber",
          method: "streamingPull",
          actions: [
            { write: { subscription: `${S}/ordered`, streamAckDeadlineSeconds: 10 } },
            { waitMs: 700 },
            { write: { ackIds: ["{{ackId:stream}}", "{{ackId:stream#2}}", "{{ackId:stream#3}}"] } },
            { waitMs: 300 },
            { end: true },
          ],
        },
      },
      publish("publish-more", "orders", [msg("a4", undefined, "a")]),
      pull("pull-after", "ordered", 10),
    ],
  },
  // ---------------------------------------------------------------- push
  {
    id: "push-delivery",
    category: "push",
    title: "push envelope, attributes header, pull on a push subscription and switching",
    steps: [
      topic("topic", "orders"),
      subscription("push-sub", "push-sub", "orders", { pushConfig: { pushEndpoint: "{{pushOrigin}}/hook?x=1", attributes: { "x-goog-version": "v1beta1" } } }),
      publish("publish", "orders", [msg("p1", { a: "one" }, "ok"), msg("p2")]),
      pushes("pushed", 2, 3000),
      pull("pull-on-push-sub", "push-sub", 5),
      sub("to-pull", "modifyPushConfig", { subscription: `${S}/push-sub`, pushConfig: {} }),
      publish("publish-pull-mode", "orders", [msg("p3")]),
      pushes("no-pushes", 0, 500),
      pull("pull-in-pull-mode", "push-sub", 5),
      sub("to-push-with-outstanding", "modifyPushConfig", { subscription: `${S}/push-sub`, pushConfig: { pushEndpoint: "{{pushOrigin}}/hook2" } }),
      pushes("still-leased", 0, 800),
      publish("publish-push-again", "orders", [msg("p4")]),
      pushes("pushed-again", 1, 3000),
      modify("nack-outstanding", "push-sub", ["{{ackId:pull-in-pull-mode}}"], 0),
      pushes("pushed-after-nack", 1, 3000),
      sub("get", "getSubscription", { subscription: `${S}/push-sub` }),
    ],
  },
  {
    id: "push-retry",
    category: "push",
    title: "push retries on non-2xx endpoint answers",
    steps: [
      topic("topic", "orders"),
      subscription("push-sub", "push-sub", "orders", { pushConfig: { pushEndpoint: "{{pushOrigin}}/hook" } }),
      pushStatus("endpoint-500", 500),
      publish("publish", "orders", [msg("retry-me")]),
      pushes("retried-500", 3, 4000),
      pushStatus("endpoint-404", 404),
      pushes("retried-404", 2, 3000),
      pushStatus("endpoint-200", 200),
      pushes("delivered", 1, 3000),
      pushes("stops", 0, 1500),
      pushStatus("endpoint-204", 204),
      publish("publish-204", "orders", [msg("ok-204")]),
      pushes("delivered-204", 1, 3000),
      pushStatus("endpoint-302", 302),
      publish("publish-302", "orders", [msg("redirected")]),
      pushes("retried-302", 2, 3000),
      pushStatus("endpoint-ok", 200),
      pushes("delivered-after-302", 1, 3000),
    ],
  },
  // ---------------------------------------------------------------- schemas
  {
    id: "schemas-avro",
    category: "schemas",
    title: "Avro schema create/get/list/commit/rollback/delete and validation",
    steps: [
      sch("create", "createSchema", { parent: PROJECT, schemaId: "readings", schema: { type: "AVRO", definition: AVRO_RECORD } }),
      sch("create-duplicate", "createSchema", { parent: PROJECT, schemaId: "readings", schema: { type: "AVRO", definition: AVRO_RECORD } }),
      sch("create-invalid-json", "createSchema", { parent: PROJECT, schemaId: "broken", schema: { type: "AVRO", definition: "{not avro" } }),
      sch("create-invalid-avro", "createSchema", { parent: PROJECT, schemaId: "broken", schema: { type: "AVRO", definition: JSON.stringify({ type: "record", name: "X" }) } }),
      sch("create-empty-definition", "createSchema", { parent: PROJECT, schemaId: "empty", schema: { type: "AVRO", definition: "" } }),
      sch("create-no-type", "createSchema", { parent: PROJECT, schemaId: "untyped", schema: { definition: AVRO_RECORD } }),
      sch("create-protobuf", "createSchema", { parent: PROJECT, schemaId: "proto", schema: { type: "PROTOCOL_BUFFER", definition: 'syntax = "proto3"; message M { string a = 1; }' } }),
      sch("create-no-id", "createSchema", { parent: PROJECT, schema: { type: "AVRO", definition: AVRO_RECORD } }),
      sch("create-name-only", "createSchema", { parent: PROJECT, schema: { name: `${SCHEMA}/named`, type: "AVRO", definition: AVRO_RECORD } }),
      sch("create-short-id", "createSchema", { parent: PROJECT, schemaId: "ab", schema: { type: "AVRO", definition: AVRO_RECORD } }),
      sch("create-goog-id", "createSchema", { parent: PROJECT, schemaId: "goog-schema", schema: { type: "AVRO", definition: AVRO_RECORD } }),
      sch("create-bad-parent", "createSchema", { parent: "nope", schemaId: "readings2", schema: { type: "AVRO", definition: AVRO_RECORD } }),
      sch("create-primitive", "createSchema", { parent: PROJECT, schemaId: "primitive", schema: { type: "AVRO", definition: '"string"' } }),
      sch("get", "getSchema", { name: `${SCHEMA}/readings` }),
      sch("get-basic", "getSchema", { name: `${SCHEMA}/readings`, view: "BASIC" }),
      sch("get-full", "getSchema", { name: `${SCHEMA}/readings`, view: "FULL" }),
      sch("get-missing", "getSchema", { name: `${SCHEMA}/missing-schema` }),
      sch("get-invalid", "getSchema", { name: "readings" }),
      sch("list", "listSchemas", { parent: PROJECT }),
      sch("list-full", "listSchemas", { parent: PROJECT, view: "FULL" }),
      sch("list-page-1", "listSchemas", { parent: PROJECT, pageSize: 1 }),
      sch("list-page-2", "listSchemas", { parent: PROJECT, pageSize: 1, pageToken: `${SCHEMA}/readings` }),
      sch("list-other-project", "listSchemas", { parent: OTHER_PROJECT }),
      sch("commit", "commitSchema", { name: `${SCHEMA}/readings`, schema: { name: `${SCHEMA}/readings`, type: "AVRO", definition: AVRO_RECORD_V2 } }),
      sch("commit-invalid", "commitSchema", { name: `${SCHEMA}/readings`, schema: { name: `${SCHEMA}/readings`, type: "AVRO", definition: "{bad" } }),
      sch("commit-missing", "commitSchema", { name: `${SCHEMA}/missing-schema`, schema: { type: "AVRO", definition: AVRO_RECORD } }),
      sch("commit-no-schema", "commitSchema", { name: `${SCHEMA}/readings` }),
      sch("revisions", "listSchemaRevisions", { name: `${SCHEMA}/readings` }),
      sch("revisions-basic", "listSchemaRevisions", { name: `${SCHEMA}/readings`, view: "BASIC" }),
      sch("revisions-page", "listSchemaRevisions", { name: `${SCHEMA}/readings`, pageSize: 1 }),
      sch("revisions-missing", "listSchemaRevisions", { name: `${SCHEMA}/missing-schema` }),
      sch("get-at-revision", "getSchema", { name: `${SCHEMA}/readings@{{revisionId:create}}` }),
      sch("get-at-missing-revision", "getSchema", { name: `${SCHEMA}/readings@deadbeef` }),
      sch("get-latest", "getSchema", { name: `${SCHEMA}/readings` }),
      sch("rollback", "rollbackSchema", { name: `${SCHEMA}/readings`, revisionId: "{{revisionId:create}}" }),
      sch("rollback-missing-revision", "rollbackSchema", { name: `${SCHEMA}/readings`, revisionId: "deadbeef" }),
      sch("rollback-missing-schema", "rollbackSchema", { name: `${SCHEMA}/missing-schema`, revisionId: "{{revisionId:create}}" }),
      sch("revisions-after-rollback", "listSchemaRevisions", { name: `${SCHEMA}/readings` }),
      sch("delete-revision", "deleteSchemaRevision", { name: `${SCHEMA}/readings`, revisionId: "{{revisionId:commit}}" }),
      sch("delete-revision-at-name", "deleteSchemaRevision", { name: `${SCHEMA}/readings@{{revisionId:commit}}` }),
      sch("delete-revision-missing", "deleteSchemaRevision", { name: `${SCHEMA}/readings`, revisionId: "deadbeef" }),
      sch("revisions-after-delete", "listSchemaRevisions", { name: `${SCHEMA}/readings` }),
      sch("delete-last-revision", "deleteSchemaRevision", { name: `${SCHEMA}/primitive@{{revisionId:create-primitive}}` }),
      sch("validate-ok", "validateSchema", { parent: PROJECT, schema: { type: "AVRO", definition: AVRO_RECORD } }),
      sch("validate-bad", "validateSchema", { parent: PROJECT, schema: { type: "AVRO", definition: "{bad" } }),
      sch("validate-no-type", "validateSchema", { parent: PROJECT, schema: { definition: AVRO_RECORD } }),
      sch("validate-protobuf", "validateSchema", { parent: PROJECT, schema: { type: "PROTOCOL_BUFFER", definition: 'syntax = "proto3";' } }),
      sch("validate-message-by-name", "validateMessage", { parent: PROJECT, name: `${SCHEMA}/readings`, message: b64(JSON.stringify({ sensor: "s1", value: 1.5 })), encoding: "JSON" }),
      sch("validate-message-by-name-bad", "validateMessage", { parent: PROJECT, name: `${SCHEMA}/readings`, message: b64(JSON.stringify({ sensor: 1 })), encoding: "JSON" }),
      sch("validate-message-by-schema", "validateMessage", { parent: PROJECT, schema: { type: "AVRO", definition: '"string"' }, message: b64('"x"'), encoding: "JSON" }),
      sch("validate-message-binary", "validateMessage", { parent: PROJECT, schema: { type: "AVRO", definition: '"string"' }, message: Buffer.from([2, 120]).toString("base64"), encoding: "BINARY" }),
      sch("validate-message-binary-bad", "validateMessage", { parent: PROJECT, schema: { type: "AVRO", definition: '"string"' }, message: Buffer.from([255, 255, 255]).toString("base64"), encoding: "BINARY" }),
      sch("validate-message-no-encoding", "validateMessage", { parent: PROJECT, schema: { type: "AVRO", definition: '"string"' }, message: b64('"x"') }),
      sch("validate-message-no-schema", "validateMessage", { parent: PROJECT, message: b64('"x"'), encoding: "JSON" }),
      sch("validate-message-missing-schema", "validateMessage", { parent: PROJECT, name: `${SCHEMA}/missing-schema`, message: b64('"x"'), encoding: "JSON" }),
      sch("validate-message-at-revision", "validateMessage", { parent: PROJECT, name: `${SCHEMA}/readings@{{revisionId:create}}`, message: b64(JSON.stringify({ sensor: "s1", value: 1.5 })), encoding: "JSON" }),
      sch("delete", "deleteSchema", { name: `${SCHEMA}/readings` }),
      sch("delete-again", "deleteSchema", { name: `${SCHEMA}/readings` }),
      sch("get-deleted", "getSchema", { name: `${SCHEMA}/readings` }),
      sch("list-after-delete", "listSchemas", { parent: PROJECT }),
    ],
  },
  {
    id: "schemas-http",
    category: "schemas",
    title: "schema operations over HTTP/JSON",
    steps: [
      http("create", "POST", `/v1/${SCHEMA}?schemaId=readings`, { type: "AVRO", definition: AVRO_RECORD }),
      http("create-duplicate", "POST", `/v1/${SCHEMA}?schemaId=readings`, { type: "AVRO", definition: AVRO_RECORD }),
      http("create-no-id", "POST", `/v1/${SCHEMA}`, { type: "AVRO", definition: AVRO_RECORD }),
      http("create-invalid", "POST", `/v1/${SCHEMA}?schemaId=broken`, { type: "AVRO", definition: "{bad" }),
      http("create-protobuf", "POST", `/v1/${SCHEMA}?schemaId=proto`, { type: "PROTOCOL_BUFFER", definition: 'syntax = "proto3";' }),
      http("get", "GET", `/v1/${SCHEMA}/readings`),
      http("get-basic", "GET", `/v1/${SCHEMA}/readings?view=BASIC`),
      http("get-missing", "GET", `/v1/${SCHEMA}/missing-schema`),
      http("list", "GET", `/v1/${SCHEMA}`),
      http("list-full", "GET", `/v1/${SCHEMA}?view=FULL`),
      http("commit", "POST", `/v1/${SCHEMA}/readings:commit`, { schema: { name: `${SCHEMA}/readings`, type: "AVRO", definition: AVRO_RECORD_V2 } }),
      http("revisions", "GET", `/v1/${SCHEMA}/readings:listRevisions`),
      http("revisions-basic", "GET", `/v1/${SCHEMA}/readings:listRevisions?view=BASIC`),
      http("get-at-revision", "GET", `/v1/${SCHEMA}/readings@{{revisionId:create}}`),
      http("rollback", "POST", `/v1/${SCHEMA}/readings:rollback`, { revisionId: "{{revisionId:create}}" }),
      http("delete-revision", "DELETE", `/v1/${SCHEMA}/readings@{{revisionId:commit}}:deleteRevision`),
      http("delete-revision-query", "DELETE", `/v1/${SCHEMA}/readings:deleteRevision?revisionId={{revisionId:rollback}}`),
      http("revisions-after", "GET", `/v1/${SCHEMA}/readings:listRevisions`),
      http("validate", "POST", `/v1/${SCHEMA}:validate`, { schema: { type: "AVRO", definition: AVRO_RECORD } }),
      http("validate-bad", "POST", `/v1/${SCHEMA}:validate`, { schema: { type: "AVRO", definition: "{bad" } }),
      http("validate-message", "POST", `/v1/${SCHEMA}:validateMessage`, { name: `${SCHEMA}/readings`, message: b64(JSON.stringify({ sensor: "s1", value: 1.5 })), encoding: "JSON" }),
      http("validate-message-bad", "POST", `/v1/${SCHEMA}:validateMessage`, { name: `${SCHEMA}/readings`, message: b64("{}"), encoding: "JSON" }),
      http("delete", "DELETE", `/v1/${SCHEMA}/readings`),
      http("delete-again", "DELETE", `/v1/${SCHEMA}/readings`),
      http("list-after", "GET", `/v1/${SCHEMA}`),
    ],
  },
  {
    id: "schema-topic-binding",
    category: "schemas",
    title: "topics bound to a schema validate published messages",
    steps: [
      sch("create", "createSchema", { parent: PROJECT, schemaId: "readings", schema: { type: "AVRO", definition: AVRO_RECORD } }),
      topic("topic-json", "readings-json", { schemaSettings: { schema: `${SCHEMA}/readings`, encoding: "JSON" } }),
      topic("topic-binary", "readings-binary", { schemaSettings: { schema: `${SCHEMA}/readings`, encoding: "BINARY" } }),
      topic("topic-no-encoding", "readings-unspecified", { schemaSettings: { schema: `${SCHEMA}/readings` } }),
      topic("topic-missing-schema", "readings-missing", { schemaSettings: { schema: `${SCHEMA}/missing-schema`, encoding: "JSON" } }),
      topic("topic-invalid-schema-name", "readings-invalid", { schemaSettings: { schema: "readings", encoding: "JSON" } }),
      topic("topic-revision-range", "readings-range", { schemaSettings: { schema: `${SCHEMA}/readings`, encoding: "JSON", firstRevisionId: "{{revisionId:create}}", lastRevisionId: "{{revisionId:create}}" } }),
      topic("topic-bad-revision-range", "readings-bad-range", { schemaSettings: { schema: `${SCHEMA}/readings`, encoding: "JSON", firstRevisionId: "deadbeef" } }),
      subscription("sub-json", "sub-json", "readings-json"),
      subscription("sub-binary", "sub-binary", "readings-binary"),
      publish("publish-json-ok", "readings-json", [{ data: b64(JSON.stringify({ sensor: "s1", value: 1.5 })) }]),
      publish("publish-json-bad", "readings-json", [{ data: b64(JSON.stringify({ sensor: 1 })) }]),
      publish("publish-json-not-json", "readings-json", [{ data: b64("not json") }]),
      publish("publish-json-mixed", "readings-json", [{ data: b64(JSON.stringify({ sensor: "s1", value: 1.5 })) }, { data: b64("bad") }]),
      publish("publish-json-empty-data-attributes", "readings-json", [{ attributes: { a: "b" } }]),
      publish("publish-binary-ok", "readings-binary", [{ data: Buffer.concat([Buffer.from([4]), Buffer.from("s1"), Buffer.from([0, 0, 0, 0, 0, 0, 248, 63])]).toString("base64") }]),
      publish("publish-binary-bad", "readings-binary", [{ data: b64("{}") }]),
      publish("publish-unspecified", "readings-unspecified", [{ data: b64(JSON.stringify({ sensor: "s1", value: 1.5 })) }]),
      pull("pull-json", "sub-json", 10),
      pull("pull-binary", "sub-binary", 10),
      pub("get-topic", "getTopic", { topic: `${T}/readings-json` }),
      pub("update-encoding", "updateTopic", { topic: { name: `${T}/readings-json`, schemaSettings: { schema: `${SCHEMA}/readings`, encoding: "BINARY" } }, updateMask: { paths: ["schema_settings"] } }),
      pub("update-clear-schema", "updateTopic", { topic: { name: `${T}/readings-json`, schemaSettings: {} }, updateMask: { paths: ["schema_settings"] } }),
      publish("publish-after-clear", "readings-json", [{ data: b64("anything") }]),
      sch("commit", "commitSchema", { name: `${SCHEMA}/readings`, schema: { name: `${SCHEMA}/readings`, type: "AVRO", definition: AVRO_RECORD_V2 } }),
      publish("publish-after-commit", "readings-binary", [{ data: Buffer.concat([Buffer.from([4]), Buffer.from("s1"), Buffer.from([0, 0, 0, 0, 0, 0, 248, 63])]).toString("base64") }]),
      sch("delete-schema", "deleteSchema", { name: `${SCHEMA}/readings` }),
      publish("publish-after-schema-delete", "readings-binary", [{ data: b64("x") }]),
      pub("get-topic-after-schema-delete", "getTopic", { topic: `${T}/readings-binary` }),
      http("publish-http-json-bad", "POST", `/v1/${T}/readings-range:publish`, { messages: [{ data: b64("nope") }] }),
    ],
  },
  // ---------------------------------------------------------------- misc
  {
    id: "iam",
    category: "iam",
    title: "IAM policy calls on topics, subscriptions and schemas",
    steps: [
      topic("topic", "orders"),
      subscription("sub", "sub-a", "orders"),
      iam("get-topic", "getIamPolicy", { resource: `${T}/orders` }),
      iam("set-topic", "setIamPolicy", { resource: `${T}/orders`, policy: { bindings: [{ role: "roles/pubsub.publisher", members: ["user:a@example.test"] }] } }),
      iam("test-topic", "testIamPermissions", { resource: `${T}/orders`, permissions: ["pubsub.topics.publish"] }),
      iam("get-subscription", "getIamPolicy", { resource: `${S}/sub-a` }),
      iam("get-missing", "getIamPolicy", { resource: `${T}/missing-topic` }),
      http("get-topic-http", "GET", `/v1/${T}/orders:getIamPolicy`),
      http("set-topic-http", "POST", `/v1/${T}/orders:setIamPolicy`, { policy: { bindings: [] } }),
      http("test-topic-http", "POST", `/v1/${T}/orders:testIamPermissions`, { permissions: ["pubsub.topics.publish"] }),
      http("get-subscription-http", "GET", `/v1/${S}/sub-a:getIamPolicy`),
      http("get-schema-http", "GET", `/v1/${SCHEMA}/x:getIamPolicy`),
    ],
  },
  {
    id: "http-surface",
    category: "http",
    title: "unknown paths, methods and bodies on the HTTP surface",
    steps: [
      http("put-topic", "PUT", `/v1/${T}/orders`, {}),
      http("root", "GET", "/"),
      http("v1-root", "GET", "/v1"),
      http("projects", "GET", "/v1/projects"),
      http("project", "GET", `/v1/${PROJECT}`),
      http("unknown-collection", "GET", `/v1/${PROJECT}/nothing`),
      http("unknown-verb", "POST", `/v1/${T}/orders:frobnicate`, {}),
      http("post-topic", "POST", `/v1/${T}/orders`, {}),
      http("get-publish", "GET", `/v1/${T}/orders:publish`),
      http("put-publish", "PUT", `/v1/${T}/orders:publish`, { messages: [{ data: b64("x") }] }),
      http("delete-publish", "DELETE", `/v1/${T}/orders:publish`),
      http("trailing-slash", "GET", `/v1/${T}/orders/`),
      http("double-slash", "GET", `/v1//${T}/orders`),
      http("encoded-colon", "POST", `/v1/${T}/orders%3Apublish`, { messages: [{ data: b64("x") }] }),
      http("query-alt", "GET", `/v1/${T}/orders?alt=json`),
      http("query-pretty", "GET", `/v1/${T}/orders?prettyPrint=false`),
      http("query-unknown", "GET", `/v1/${T}/orders?bogus=1`),
      http("v2", "GET", `/v2/${T}/orders`),
      http("no-version", "GET", `/${T}/orders`),
      http("head", "HEAD", `/v1/${T}/orders`),
      http("options", "OPTIONS", `/v1/${T}/orders`),
      http("bad-json", "PUT", `/v1/${T}/broken`, "{bad json"),
      http("json-array", "PUT", `/v1/${T}/broken`, "[]"),
      http("json-string", "PUT", `/v1/${T}/broken`, '"text"'),
      http("empty-body", "PUT", `/v1/${T}/emptybody`, ""),
      http("unknown-field", "PUT", `/v1/${T}/unknown-field`, { bogus: true }),
      http("wrong-type", "PUT", `/v1/${T}/wrong-type`, { labels: "not-a-map" }),
      http("snake-case-field", "PUT", `/v1/${T}/snake`, { message_retention_duration: "600s" }),
      http("get-snake", "GET", `/v1/${T}/snake`),
      http("int-as-string", "PUT", `/v1/${S}/sub-int`, { topic: `${T}/orders`, ackDeadlineSeconds: "30" }),
      http("bool-as-string", "PUT", `/v1/${S}/sub-bool`, { topic: `${T}/orders`, retainAckedMessages: "true" }),
      http("null-field", "PUT", `/v1/${S}/sub-null`, { topic: `${T}/orders`, labels: null }),
      http("duration-fraction", "PUT", `/v1/${S}/sub-fraction`, { topic: `${T}/orders`, messageRetentionDuration: "600.5s" }),
      http("duration-no-unit", "PUT", `/v1/${S}/sub-no-unit`, { topic: `${T}/orders`, messageRetentionDuration: "600" }),
      http("enum-unknown", "POST", `/v1/${SCHEMA}?schemaId=enum-unknown`, { type: "NOPE", definition: '"string"' }),
      http("timestamp-seek", "POST", `/v1/${S}/sub-int:seek`, { time: "not-a-time" }),
      http("bytes-invalid", "POST", `/v1/${T}/orders:publish`, { messages: [{ data: "%%%" }] }),
      http("bytes-url-safe", "POST", `/v1/${T}/orders:publish`, { messages: [{ data: "-_-_" }] }, "URL-safe base64"),
      http("bytes-unpadded", "POST", `/v1/${T}/orders:publish`, { messages: [{ data: "YWJj" }] }),
      http("content-type-text", "PUT", `/v1/${T}/text-body`, "{}"),
    ],
  },
  {
    id: "projects",
    category: "misc",
    title: "resources are scoped by project and cross-project references",
    steps: [
      topic("topic", "orders"),
      pub("other-topic", "createTopic", { name: `${OTHER_PROJECT}/topics/orders` }),
      pub("list-a", "listTopics", { project: PROJECT }),
      pub("list-b", "listTopics", { project: OTHER_PROJECT }),
      sub("cross-subscription", "createSubscription", { name: `${OTHER_PROJECT}/subscriptions/cross`, topic: `${T}/orders` }),
      subscription("local-subscription", "local", "orders"),
      publish("publish", "orders", [msg("x")]),
      sub("pull-cross", "pull", { subscription: `${OTHER_PROJECT}/subscriptions/cross`, maxMessages: 5, returnImmediately: true }),
      pull("pull-local", "local", 5),
      sub("list-subs-a", "listSubscriptions", { project: PROJECT }),
      sub("list-subs-b", "listSubscriptions", { project: OTHER_PROJECT }),
      pub("topic-subscriptions", "listTopicSubscriptions", { topic: `${T}/orders` }),
      pub("get-other", "getTopic", { topic: `${OTHER_PROJECT}/topics/orders` }),
      pub("delete-other", "deleteTopic", { topic: `${OTHER_PROJECT}/topics/orders` }),
      pub("get-local-after", "getTopic", { topic: `${T}/orders` }),
      sub("cross-snapshot", "createSnapshot", { name: `${OTHER_PROJECT}/snapshots/cross-snap`, subscription: `${S}/local` }),
      sub("list-snapshots-a", "listSnapshots", { project: PROJECT }),
      sub("list-snapshots-b", "listSnapshots", { project: OTHER_PROJECT }),
    ],
  },
  {
    id: "exactly-once",
    category: "pull",
    title: "exactly-once delivery flags on pull and acknowledge",
    steps: [
      topic("topic", "orders"),
      subscription("sub", "exactly-once", "orders", { enableExactlyOnceDelivery: true, ackDeadlineSeconds: 10 }),
      publish("publish", "orders", [msg("one"), msg("two")]),
      pull("pull", "exactly-once", 5),
      ack("ack", "exactly-once", ["{{ackId:pull}}"]),
      ack("ack-again", "exactly-once", ["{{ackId:pull}}"]),
      modify("modify", "exactly-once", ["{{ackId:pull#2}}"], 30),
      {
        id: "stream",
        stream: {
          service: "Subscriber",
          method: "streamingPull",
          actions: [{ write: { subscription: `${S}/exactly-once`, streamAckDeadlineSeconds: 10 } }, { waitMs: 700 }, { end: true }],
        },
      },
      pull("pull-after", "exactly-once", 5),
      sub("get", "getSubscription", { subscription: `${S}/exactly-once` }),
    ],
  },
  {
    id: "retention",
    category: "pull",
    title: "topic and subscription message retention settings",
    steps: [
      topic("topic-retained", "retained", { messageRetentionDuration: { seconds: "600" } }),
      subscription("sub-late", "late", "retained"),
      publish("publish-before-sub", "retained", [msg("before")]),
      subscription("sub-after-publish", "after", "retained"),
      publish("publish-after-sub", "retained", [msg("after")]),
      pull("pull-late", "late", 5),
      pull("pull-after", "after", 5),
      sub("seek-after-epoch", "seek", { subscription: `${S}/after`, time: { seconds: "0" } }),
      pull("pull-after-seek", "after", 5),
      sub("update-retention", "updateSubscription", { subscription: { name: `${S}/late`, messageRetentionDuration: { seconds: "2678400" } }, updateMask: { paths: ["message_retention_duration"] } }),
      sub("get-late", "getSubscription", { subscription: `${S}/late` }),
    ],
  },
  {
    id: "http-list-paging",
    category: "http",
    title: "pagination parameters over HTTP/JSON for every list",
    steps: [
      http("t1", "PUT", `/v1/${T}/alpha`, {}),
      http("t2", "PUT", `/v1/${T}/beta`, {}),
      http("t3", "PUT", `/v1/${T}/gamma`, {}),
      http("s1", "PUT", `/v1/${S}/alpha-sub`, { topic: `${T}/alpha` }),
      http("s2", "PUT", `/v1/${S}/beta-sub`, { topic: `${T}/alpha` }),
      http("s3", "PUT", `/v1/${S}/gamma-sub`, { topic: `${T}/beta` }),
      http("snap1", "PUT", `/v1/${SNAP}/alpha-snap`, { subscription: `${S}/alpha-sub` }),
      http("snap2", "PUT", `/v1/${SNAP}/beta-snap`, { subscription: `${S}/beta-sub` }),
      http("sch1", "POST", `/v1/${SCHEMA}?schemaId=alpha-schema`, { type: "AVRO", definition: '"string"' }),
      http("sch2", "POST", `/v1/${SCHEMA}?schemaId=beta-schema`, { type: "AVRO", definition: '"int"' }),
      http("topics-1", "GET", `/v1/${T}?pageSize=2`),
      http("topics-2", "GET", `/v1/${T}?pageSize=2&pageToken=${encodeURIComponent(`${T}/gamma`)}`),
      http("topics-negative", "GET", `/v1/${T}?pageSize=-5`),
      http("subs-1", "GET", `/v1/${S}?pageSize=2`),
      http("subs-2", "GET", `/v1/${S}?pageSize=2&pageToken=${encodeURIComponent(`${S}/gamma-sub`)}`),
      http("topic-subs-1", "GET", `/v1/${T}/alpha/subscriptions?pageSize=1`),
      http("topic-subs-2", "GET", `/v1/${T}/alpha/subscriptions?pageSize=1&pageToken=${encodeURIComponent(`${S}/beta-sub`)}`),
      http("snapshots-1", "GET", `/v1/${SNAP}?pageSize=1`),
      http("snapshots-2", "GET", `/v1/${SNAP}?pageSize=1&pageToken=${encodeURIComponent(`${SNAP}/beta-snap`)}`),
      http("topic-snapshots", "GET", `/v1/${T}/alpha/snapshots?pageSize=1`),
      http("schemas-1", "GET", `/v1/${SCHEMA}?pageSize=1&view=BASIC`),
      http("schemas-2", "GET", `/v1/${SCHEMA}?pageSize=1&pageToken=${encodeURIComponent(`${SCHEMA}/beta-schema`)}`),
    ],
  },
  {
    id: "fan-out",
    category: "pull",
    title: "every subscription gets its own copy; subscriptions created later start empty",
    steps: [
      topic("topic", "orders"),
      subscription("sub-a", "sub-a", "orders"),
      subscription("sub-b", "sub-b", "orders", { ackDeadlineSeconds: 20 }),
      publish("publish", "orders", [msg("one", { n: "one" }), msg("two", { n: "two" })]),
      subscription("sub-late", "sub-late", "orders"),
      publish("publish-later", "orders", [msg("three")]),
      pull("pull-a", "sub-a", 10),
      pull("pull-b", "sub-b", 10),
      pull("pull-late", "sub-late", 10),
      ack("ack-a-one", "sub-a", ["{{ackId:pull-a}}"]),
      modify("nack-b-one", "sub-b", ["{{ackId:pull-b}}"], 0),
      pull("pull-a-again", "sub-a", 10),
      pull("pull-b-again", "sub-b", 10),
      sub("delete-b", "deleteSubscription", { subscription: `${S}/sub-b` }),
      publish("publish-after-delete", "orders", [msg("four")]),
      pull("pull-a-final", "sub-a", 10),
      pull("pull-late-final", "sub-late", 10),
      sub("list", "listSubscriptions", { project: PROJECT }),
    ],
  },
  {
    id: "dead-letter-and-filter-http",
    category: "http",
    title: "deliveryAttempt, dead-letter forwarding, filters and error mapping over HTTP/JSON",
    steps: [
      http("topic", "PUT", `/v1/${T}/orders`, {}),
      http("dead-letter-topic", "PUT", `/v1/${T}/dead-letters`, {}),
      http("dlq-sub", "PUT", `/v1/${S}/dlq-sub`, { topic: `${T}/dead-letters` }),
      http("sub", "PUT", `/v1/${S}/sub-a`, { topic: `${T}/orders`, deadLetterPolicy: { deadLetterTopic: `${T}/dead-letters`, maxDeliveryAttempts: 5 }, filter: 'attributes.kind = "poison"' }),
      http("sub-bad-filter", "PUT", `/v1/${S}/sub-b`, { topic: `${T}/orders`, filter: "attributes.kind =" }),
      http("sub-few-attempts", "PUT", `/v1/${S}/sub-c`, { topic: `${T}/orders`, deadLetterPolicy: { deadLetterTopic: `${T}/dead-letters`, maxDeliveryAttempts: 2 } }),
      http("sub-dlq-missing", "PUT", `/v1/${S}/sub-d`, { topic: `${T}/orders`, deadLetterPolicy: { deadLetterTopic: `${T}/missing-topic` } }),
      http("publish", "POST", `/v1/${T}/orders:publish`, { messages: [{ data: b64("poison"), attributes: { kind: "poison" } }, { data: b64("filtered-out"), attributes: { kind: "other" } }] }),
      http("attempt-1", "POST", `/v1/${S}/sub-a:pull`, { maxMessages: 5, returnImmediately: true }),
      http("nack-1", "POST", `/v1/${S}/sub-a:modifyAckDeadline`, { ackIds: ["{{ackId:attempt-1}}"], ackDeadlineSeconds: 0 }),
      http("attempt-2", "POST", `/v1/${S}/sub-a:pull`, { maxMessages: 5, returnImmediately: true }),
      http("nack-2", "POST", `/v1/${S}/sub-a:modifyAckDeadline`, { ackIds: ["{{ackId:attempt-2}}"], ackDeadlineSeconds: 0 }),
      http("attempt-3", "POST", `/v1/${S}/sub-a:pull`, { maxMessages: 5, returnImmediately: true }),
      http("nack-3", "POST", `/v1/${S}/sub-a:modifyAckDeadline`, { ackIds: ["{{ackId:attempt-3}}"], ackDeadlineSeconds: 0 }),
      http("attempt-4", "POST", `/v1/${S}/sub-a:pull`, { maxMessages: 5, returnImmediately: true }),
      http("nack-4", "POST", `/v1/${S}/sub-a:modifyAckDeadline`, { ackIds: ["{{ackId:attempt-4}}"], ackDeadlineSeconds: 0 }),
      http("attempt-5", "POST", `/v1/${S}/sub-a:pull`, { maxMessages: 5, returnImmediately: true }),
      http("nack-5", "POST", `/v1/${S}/sub-a:modifyAckDeadline`, { ackIds: ["{{ackId:attempt-5}}"], ackDeadlineSeconds: 0 }),
      http("attempt-6", "POST", `/v1/${S}/sub-a:pull`, { maxMessages: 5, returnImmediately: true }),
      sleep("settle", 500),
      http("dead-letters", "POST", `/v1/${S}/dlq-sub:pull`, { maxMessages: 5, returnImmediately: true }),
      http("delete-topic", "DELETE", `/v1/${T}/orders`),
      http("get-sub-after-topic-delete", "GET", `/v1/${S}/sub-a`),
      http("publish-deleted", "POST", `/v1/${T}/orders:publish`, { messages: [{ data: b64("x") }] }),
      http("snapshot-of-deleted-topic-sub", "PUT", `/v1/${SNAP}/orphan`, { subscription: `${S}/sub-a` }),
    ],
  },
  {
    id: "push-envelope",
    category: "push",
    title: "push envelopes for every message shape and push subscriptions' lifecycle",
    steps: [
      topic("topic", "orders"),
      publish("publish-before-sub", "orders", [msg("before")]),
      subscription("push-sub", "push-sub", "orders", { pushConfig: { pushEndpoint: "{{pushOrigin}}/hook" } }),
      pushes("no-backfill", 0, 600),
      publish("publish-shapes", "orders", [msg("with-key", { a: "one", b: "two" }, "key-1"), { attributes: { only: "attributes" } }, msg("plain")]),
      pushes("pushed-shapes", 3, 3000),
      sub("update-to-pull", "updateSubscription", { subscription: { name: `${S}/push-sub`, pushConfig: {} }, updateMask: { paths: ["push_config"] } }),
      publish("publish-pull-mode", "orders", [msg("pull-mode")]),
      pushes("no-push-in-pull-mode", 0, 600),
      pull("pull-in-pull-mode", "push-sub", 10),
      ack("ack-pull-mode", "push-sub", ["{{ackId:pull-in-pull-mode}}"]),
      sub("update-to-push", "updateSubscription", { subscription: { name: `${S}/push-sub`, pushConfig: { pushEndpoint: "{{pushOrigin}}/hook-2", attributes: { "x-goog-version": "v1" } } }, updateMask: { paths: ["push_config"] } }),
      publish("publish-push-mode", "orders", [msg("push-mode")]),
      pushes("pushed-with-attributes", 1, 3000),
      sub("delete-sub", "deleteSubscription", { subscription: `${S}/push-sub` }),
      publish("publish-after-delete", "orders", [msg("nobody")]),
      pushes("no-push-after-delete", 0, 600),
      subscription("push-sub-again", "push-sub", "orders", { pushConfig: { pushEndpoint: "{{pushOrigin}}/hook-3" } }),
      pushes("no-push-for-earlier", 0, 600),
      pub("delete-topic", "deleteTopic", { topic: `${T}/orders` }),
      sub("get-after-topic-delete", "getSubscription", { subscription: `${S}/push-sub` }),
    ],
  },
  {
    id: "streaming-pull-two-streams",
    category: "streaming",
    title: "two streams on one subscription share the backlog; ids belong to the subscription",
    steps: [
      topic("topic", "orders"),
      subscription("sub", "sub-a", "orders", { ackDeadlineSeconds: 10 }),
      subscription("other", "sub-b", "orders", { ackDeadlineSeconds: 10 }),
      publish("publish", "orders", [msg("one"), msg("two")]),
      {
        id: "stream-a",
        stream: {
          service: "Subscriber",
          method: "streamingPull",
          actions: [{ write: { subscription: `${S}/sub-a`, streamAckDeadlineSeconds: 10 } }, { waitMs: 700 }, { end: true }],
        },
      },
      {
        id: "stream-b-other-ids",
        note: "acknowledging sub-a's ids on sub-b's stream",
        stream: {
          service: "Subscriber",
          method: "streamingPull",
          actions: [
            { write: { subscription: `${S}/sub-b`, streamAckDeadlineSeconds: 10 } },
            { waitMs: 500 },
            { write: { ackIds: ["{{ackId:stream-a}}"] } },
            { waitMs: 500 },
            { end: true },
          ],
        },
      },
      ack("ack-by-pull-path", "sub-a", ["{{ackId:stream-a}}"]),
      modify("modify-by-pull-path", "sub-a", ["{{ackId:stream-a#2}}"], 0),
      pull("pull-after", "sub-a", 10),
      pull("pull-b", "sub-b", 10),
      {
        id: "stream-modify-pull-ids",
        note: "modifying a pull ack id from a stream",
        stream: {
          service: "Subscriber",
          method: "streamingPull",
          actions: [
            { write: { subscription: `${S}/sub-a`, streamAckDeadlineSeconds: 10, modifyDeadlineAckIds: ["{{ackId:pull-after}}"], modifyDeadlineSeconds: [0] } },
            { waitMs: 700 },
            { end: true },
          ],
        },
      },
      pull("pull-final", "sub-a", 10),
    ],
  },
  {
    id: "topic-fields-http",
    category: "topics",
    title: "topic fields over HTTP/JSON: labels, storage policy, KMS, schema settings, masks",
    steps: [
      http("create-full", "PUT", `/v1/${T}/full`, { labels: { env: "test" }, messageStoragePolicy: { allowedPersistenceRegions: ["us-central1", "europe-west1"] }, kmsKeyName: "projects/p/locations/l/keyRings/r/cryptoKeys/k", messageRetentionDuration: "1800s" }),
      http("get-full", "GET", `/v1/${T}/full`),
      http("create-schema-missing", "PUT", `/v1/${T}/with-schema`, { schemaSettings: { schema: `${SCHEMA}/missing-schema`, encoding: "JSON" } }),
      http("create-schema", "POST", `/v1/${SCHEMA}?schemaId=readings`, { type: "AVRO", definition: AVRO_RECORD }),
      http("create-with-schema", "PUT", `/v1/${T}/with-schema`, { schemaSettings: { schema: `${SCHEMA}/readings`, encoding: "JSON" } }),
      http("publish-schema-ok", "POST", `/v1/${T}/with-schema:publish`, { messages: [{ data: b64(JSON.stringify({ sensor: "s1", value: 2 })) }] }),
      http("publish-schema-bad", "POST", `/v1/${T}/with-schema:publish`, { messages: [{ data: b64("nope") }] }),
      http("patch-mask-in-body-and-query", "PATCH", `/v1/${T}/full?updateMask=message_retention_duration`, { topic: { name: `${T}/full`, messageRetentionDuration: "3600s" }, updateMask: "labels" }),
      http("patch-schema", "PATCH", `/v1/${T}/full`, { topic: { name: `${T}/full`, schemaSettings: { schema: `${SCHEMA}/readings`, encoding: "BINARY" } }, updateMask: "schema_settings" }),
      http("patch-unknown-field", "PATCH", `/v1/${T}/full`, { topic: { name: `${T}/full` }, updateMask: "bogus" }),
      http("patch-missing", "PATCH", `/v1/${T}/missing-topic`, { topic: { name: `${T}/missing-topic`, messageRetentionDuration: "3600s" }, updateMask: "message_retention_duration" }),
      http("get-after-patch", "GET", `/v1/${T}/full`),
      http("sub", "PUT", `/v1/${S}/full-sub`, { topic: `${T}/full` }),
      http("delete-topic", "DELETE", `/v1/${T}/full`),
      http("get-sub", "GET", `/v1/${S}/full-sub`),
      http("topic-subscriptions-deleted", "GET", `/v1/${T}/full/subscriptions`),
      http("delete-schema", "DELETE", `/v1/${SCHEMA}/readings`),
      http("get-with-schema-after", "GET", `/v1/${T}/with-schema`),
    ],
  },
  {
    id: "detached-and-expiration",
    category: "subscriptions",
    title: "detached subscriptions and expiration policies",
    steps: [
      topic("topic", "orders"),
      subscription("detached", "detached", "orders", { detached: true }),
      subscription("attached", "attached", "orders"),
      subscription("expiring", "expiring", "orders", { expirationPolicy: { ttl: { seconds: "86400" } } }),
      subscription("expiring-short", "expiring-short", "orders", { expirationPolicy: { ttl: { seconds: "1" } } }),
      subscription("expiring-zero", "expiring-zero", "orders", { expirationPolicy: { ttl: { seconds: "0" } } }),
      subscription("never-expiring", "never", "orders", { expirationPolicy: {} }),
      publish("publish", "orders", [msg("one")]),
      pull("pull-detached", "detached", 10),
      pull("pull-attached", "attached", 10),
      pull("pull-expiring-short", "expiring-short", 10),
      sub("get-detached", "getSubscription", { subscription: `${S}/detached` }),
      pub("topic-subscriptions", "listTopicSubscriptions", { topic: `${T}/orders` }),
      sub("attach", "updateSubscription", { subscription: { name: `${S}/detached`, detached: false }, updateMask: { paths: ["detached"] } }),
      sub("update-expiration-never", "updateSubscription", { subscription: { name: `${S}/expiring`, expirationPolicy: {} }, updateMask: { paths: ["expiration_policy"] } }),
      sub("update-expiration-ttl", "updateSubscription", { subscription: { name: `${S}/never`, expirationPolicy: { ttl: { seconds: "172800" } } }, updateMask: { paths: ["expiration_policy"] } }),
      sub("list", "listSubscriptions", { project: PROJECT }),
    ],
  },
  {
    id: "snapshot-semantics",
    category: "seek",
    title: "snapshot contents across subscriptions, acked messages and later publishes",
    steps: [
      topic("topic", "orders"),
      topic("other-topic", "other"),
      subscription("sub-a", "sub-a", "orders"),
      subscription("sub-b", "sub-b", "orders"),
      subscription("sub-other", "sub-other", "other"),
      publish("publish-1", "orders", [msg("one"), msg("two")]),
      pull("pull-a", "sub-a", 10),
      ack("ack-a-one", "sub-a", ["{{ackId:pull-a}}"]),
      sub("snapshot", "createSnapshot", { name: `${SNAP}/snap`, subscription: `${S}/sub-a` }),
      ack("ack-a-two", "sub-a", ["{{ackId:pull-a#2}}"]),
      publish("publish-2", "orders", [msg("three")]),
      pull("pull-a-three", "sub-a", 10),
      ack("ack-a-three", "sub-a", ["{{ackId:pull-a-three}}"]),
      sub("seek-a", "seek", { subscription: `${S}/sub-a`, snapshot: `${SNAP}/snap` }),
      pull("pull-a-after-seek", "sub-a", 10),
      pull("pull-b-before-seek", "sub-b", 10),
      ack("ack-b-all", "sub-b", ["{{ackId:pull-b-before-seek}}", "{{ackId:pull-b-before-seek#2}}", "{{ackId:pull-b-before-seek#3}}"]),
      sub("seek-b", "seek", { subscription: `${S}/sub-b`, snapshot: `${SNAP}/snap` }),
      pull("pull-b-after-seek", "sub-b", 10),
      sub("seek-other-topic", "seek", { subscription: `${S}/sub-other`, snapshot: `${SNAP}/snap` }),
      sub("snapshot-other-topic-name-clash", "createSnapshot", { name: `${SNAP}/snap`, subscription: `${S}/sub-other` }),
      sub("get", "getSnapshot", { snapshot: `${SNAP}/snap` }),
      pub("topic-snapshots", "listTopicSnapshots", { topic: `${T}/orders` }),
      pub("other-topic-snapshots", "listTopicSnapshots", { topic: `${T}/other` }),
      pub("delete-topic", "deleteTopic", { topic: `${T}/orders` }),
      sub("get-after-topic-delete", "getSnapshot", { snapshot: `${SNAP}/snap` }),
      sub("seek-after-topic-delete", "seek", { subscription: `${S}/sub-a`, snapshot: `${SNAP}/snap` }),
      sub("list", "listSnapshots", { project: PROJECT }),
    ],
  },
  {
    id: "modify-ack-deadline-semantics",
    category: "pull",
    title: "modifyAckDeadline extends, shortens and expires leases",
    steps: [
      topic("topic", "orders"),
      subscription("sub", "sub-a", "orders", { ackDeadlineSeconds: 10 }),
      publish("publish", "orders", [msg("one"), msg("two"), msg("three")]),
      pull("pull", "sub-a", 10),
      modify("shorten-to-one-second", "sub-a", ["{{ackId:pull}}"], 1),
      modify("extend-second", "sub-a", ["{{ackId:pull#2}}"], 30),
      modify("mixed-ids", "sub-a", ["{{ackId:pull#3}}", "garbage"], 5),
      sleep("wait-two-seconds", 2100),
      pull("pull-after-short-lease", "sub-a", 10),
      sleep("wait-past-default", 8500),
      pull("pull-after-default", "sub-a", 10),
      ack("ack-everything-seen", "sub-a", ["{{ackId:pull-after-short-lease}}", "{{ackId:pull-after-default}}"]),
      sleep("wait-past-extension", 20_000),
      pull("pull-after-extension", "sub-a", 10),
      ack("ack-last", "sub-a", ["{{ackId:pull-after-extension}}"]),
      pull("pull-empty", "sub-a", 10),
    ],
  },
];
