/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EventarcRouteImport } from './routes/eventarc'
import { Route as ExtensionsRouteImport } from './routes/extensions'
import { Route as FirestoreRouteImport } from './routes/firestore'
import { Route as FunctionsRouteImport } from './routes/functions'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as PubsubRouteImport } from './routes/pubsub'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as TasksRouteImport } from './routes/tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EventarcRoute = EventarcRouteImport.update({
  id: '/eventarc',
  path: '/eventarc',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsRoute = ExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const FirestoreRoute = FirestoreRouteImport.update({
  id: '/firestore',
  path: '/firestore',
  getParentRoute: () => rootRouteImport,
} as any)
const FunctionsRoute = FunctionsRouteImport.update({
  id: '/functions',
  path: '/functions',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const PubsubRoute = PubsubRouteImport.update({
  id: '/pubsub',
  path: '/pubsub',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/eventarc': typeof EventarcRoute
  '/extensions': typeof ExtensionsRoute
  '/firestore': typeof FirestoreRoute
  '/functions': typeof FunctionsRoute
  '/logs': typeof LogsRoute
  '/pubsub': typeof PubsubRoute
  '/requests': typeof RequestsRoute
  '/storage': typeof StorageRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/eventarc': typeof EventarcRoute
  '/extensions': typeof ExtensionsRoute
  '/firestore': typeof FirestoreRoute
  '/functions': typeof FunctionsRoute
  '/logs': typeof LogsRoute
  '/pubsub': typeof PubsubRoute
  '/requests': typeof RequestsRoute
  '/storage': typeof StorageRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/eventarc': typeof EventarcRoute
  '/extensions': typeof ExtensionsRoute
  '/firestore': typeof FirestoreRoute
  '/functions': typeof FunctionsRoute
  '/logs': typeof LogsRoute
  '/pubsub': typeof PubsubRoute
  '/requests': typeof RequestsRoute
  '/storage': typeof StorageRoute
  '/tasks': typeof TasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/eventarc'
    | '/extensions'
    | '/firestore'
    | '/functions'
    | '/logs'
    | '/pubsub'
    | '/requests'
    | '/storage'
    | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/eventarc'
    | '/extensions'
    | '/firestore'
    | '/functions'
    | '/logs'
    | '/pubsub'
    | '/requests'
    | '/storage'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/eventarc'
    | '/extensions'
    | '/firestore'
    | '/functions'
    | '/logs'
    | '/pubsub'
    | '/requests'
    | '/storage'
    | '/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  EventarcRoute: typeof EventarcRoute
  ExtensionsRoute: typeof ExtensionsRoute
  FirestoreRoute: typeof FirestoreRoute
  FunctionsRoute: typeof FunctionsRoute
  LogsRoute: typeof LogsRoute
  PubsubRoute: typeof PubsubRoute
  RequestsRoute: typeof RequestsRoute
  StorageRoute: typeof StorageRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventarc': {
      id: '/eventarc'
      path: '/eventarc'
      fullPath: '/eventarc'
      preLoaderRoute: typeof EventarcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions': {
      id: '/extensions'
      path: '/extensions'
      fullPath: '/extensions'
      preLoaderRoute: typeof ExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firestore': {
      id: '/firestore'
      path: '/firestore'
      fullPath: '/firestore'
      preLoaderRoute: typeof FirestoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/functions': {
      id: '/functions'
      path: '/functions'
      fullPath: '/functions'
      preLoaderRoute: typeof FunctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pubsub': {
      id: '/pubsub'
      path: '/pubsub'
      fullPath: '/pubsub'
      preLoaderRoute: typeof PubsubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  EventarcRoute: EventarcRoute,
  ExtensionsRoute: ExtensionsRoute,
  FirestoreRoute: FirestoreRoute,
  FunctionsRoute: FunctionsRoute,
  LogsRoute: LogsRoute,
  PubsubRoute: PubsubRoute,
  RequestsRoute: RequestsRoute,
  StorageRoute: StorageRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
